### ISSUE TITLE
How to get the JWT token to use with appSync?

### ISSUE THREAD

**Issue by horgag** [aws-amplify/amplify-flutter#105]

**Comment by fjnoyp** [comment]
Hi @horgag, that is currently not supported.  We'll discuss internally about this feature.

**Comment by horgag** [comment]
The token needed can be got by:
```
CognitoAuthSession res = await Amplify.Auth.fetchAuthSession(options: CognitoSessionOptions(getAWSCredentials: true));
      FutureOr token = res.userPoolTokens.idToken;
```

This token can be passed to `AuthLink` with graphql flutter plugin and used to query AppSync
 https://github.com/zino-app/graphql-flutter/issues/209#issuecomment-598835690

**Comment by Ashish-Nanda** [comment]
@horgag, looks like you were able to get the JWT from the AuthSession.

This information can also be found in the documentation [here](https://docs.amplify.aws/lib/auth/access_credentials/q/platform/flutter)

I'll go ahead and close this issue since your question is now resolved. If you have further issues let us know and we can look into it.

**Comment by horgag** [comment]
Important to point out that you you have to cast your result with `CognitoAuthSession` and not `AuthSession` as is in the link you provided.

**Comment by aaronsamkennedy** [comment]
Using the exact example in the documentation and trying both CognitroAuthSession and AuthSession I keep getting the following error and exceptions `AMPLIFY_FETCH_SESSION_FAILED [UNRECOGNIZED EXCEPTION, PLATFORM_EXCEPTIONS]` are there any recommendations for debugging this?

**Comment by horgag** [comment]
Has the auth plugin being added successfully to amplify?

**Comment by aaronsamkennedy** [comment]
I thought so because it appeared that the getUser code was returning my cognitoId but I suppose that I don't know how to test whether everything was configured properly or not. I tried to connect it to my current cognito userpool from an existing project instead of running it through the cli fully. Any recommendations on how to test that to see if I can determine if this is a real issue or not?

**Comment by aaronsamkennedy** [comment]
Just as a follow up I made sure that the plugging is correctly configured. I'm still getting the same error but I am able to pull some information from Cognito when signing in with getUser. I'm using the plugin inside of a provider, could that be messing up the state of the configuration?
