### ISSUE TITLE
Document the Hub Events for Amplify Cognito

### ISSUE THREAD

**Issue by offlineprogrammer** [aws-amplify/amplify-flutter#1107]
Can you list all the supported Auth Hub events

[https://docs.amplify.aws/lib/auth/auth-events/q/platform/flutter](https://docs.amplify.aws/lib/auth/auth-events/q/platform/flutter)

For example, something similar to [this](https://docs.amplify.aws/lib/datastore/datastore-events/q/platform/flutter/#networkstatus)

**Comment by Jordan-Nelson** [comment]
In addition, we should consider using an enum or a constant for this. This would be self documenting. Just looking at the [docs for iOS](https://docs.amplify.aws/lib/auth/auth-events/q/platform/ios/), it looks like either an enum for constant is used.

**Comment by Jordan-Nelson** [comment]
The docs list out all the hub events. The only issue I see with the current docs is that it isn't 100% clear that the list covers all events.

In the current developer-preview these events are enums, which makes them more discoverable & self documenting. That is, it should be clear what the full list of event types is.

@offlineprogrammer - Do we want to keep this open still? I think the docs may have been updated since this was opened and the changes in developer-preview will add further clarification.
