### ISSUE TITLE
Document how to use custom user attributes

### ISSUE THREAD

**Issue by offlineprogrammer** [aws-amplify/amplify-flutter#1180]
**Describe the bug**
Provide documentations and examples about custom user attributes

How to configure a custom user attribute?
How to update a custom user attribute?

**Additional context**
https://docs.amplify.aws/guides/authentication/managing-user-attributes/q/platform/js/#custom-attributes

**Comment by umegbewe** [comment]
Found how to do this yet?

**Comment by abdallahshaban557** [comment]
Hi @umegbewe - can you please provide us with some examples on how you would like to use custom attributes?

**Comment by Jordan-Nelson** [comment]
@umegbewe - You can add custom user attributes from the Cognito User Pool console under "General Settings" -> "Attributes" -> "Do you want to add custom attributes?" Once you have added a custom attribute, using it is not too different than using a standard attribute. Instead of using one of the const constructors on `CognitoUserAttributeKey` like `CognitoUserAttributeKey.email` you will use the `.custom` constructor - `CognitoUserAttributeKey.custom("my-custom-attribute").

You can see the docs on standard attributes [here](https://docs.amplify.aws/lib/auth/user-attributes/q/platform/flutter/).

**Comment by haverchuck** [comment]
We have added this to our docs: 

https://docs.amplify.aws/lib/auth/user-attributes/q/platform/flutter/#custom-attributes
