### ISSUE TITLE
"Hot restart" is causing a subsequent call to `Amplify.configure`

### ISSUE THREAD

**Issue by lukaselmer** [aws-amplify/amplify-flutter#122]
See https://github.com/aws-amplify/amplify-flutter/issues/94, which was closed by the author of the issue.

**Describe the bug**

PlatformException (PlatformException(AmplifyException, The client issued a subsequent call to Amplify.configure after the first had already succeeded., {cause: null, recoverySuggestion: Be sure to only call Amplify.configure once}))

**To Reproduce**

```dart
  Amplify amplify = Amplify();
  bool _isAmplifyConfigured = false;

  @override
  void initState() {
    // TODO: implement initState
    super.initState();
    _initAmplifyFlutter();
  }

  void _initAmplifyFlutter() async {
    print("init amplify");
    AmplifyAuthCognito auth = AmplifyAuthCognito();

    amplify.addPlugin(
      authPlugins: [auth],
    );
    // Initialize AmplifyFlutter
    await amplify.configure(amplifyconfig);

    setState(() {
      _isAmplifyConfigured = true;
    });
  }
```

**Platform**

Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
[x] Android
[] iOS

**Smartphone (please complete the following information):**
 - Device: Android
 - Mac

**Additional context**

The error happens when hot restarting the app.

**Comment by haverchuck** [comment]
@lukaselmer We have an open PR to address this: https://github.com/aws-amplify/amplify-flutter/pull/113
It will be included in an upcoming release.

**Comment by md-weber** [comment]
I would like to reopen this issue.
```dart
Future<void> configureAmplify() async {
  AmplifyDataStore dataStorePlugin =
      AmplifyDataStore(modelProvider: ModelProvider.instance);
  Amplify.addPlugins([dataStorePlugin]);

  try {
    await Amplify.configure(amplifyconfig);
  } on AmplifyAlreadyConfiguredException {
    print("Tried to reconfigure Amplify");
  }
}
```

The error occurs from in amplify_flutter
```dart
        // This shouldn't happen. All exceptions coming from platform for
        // amplify_flutter should have a known code. Throw an unknown error.
        throw AmplifyException(AmplifyExceptionMessages.missingExceptionMessage,
            recoverySuggestion:
                AmplifyExceptionMessages.missingRecoverySuggestion,
            underlyingException: e.toString());
      }
```

**Comment by haverchuck** [comment]
@md-weber We've reopened this and are working on a fix.

**Comment by ClarkYin** [comment]
> @md-weber We've reopened this and are working on a fix.

awesome thank you, i think i have the same issue.

**Comment by mechaadi** [comment]
Any updates on this issue?
I am getting the same error whenever I hot-restart the app or close the app using the back navigation button.

**Comment by haverchuck** [comment]
@mechaadi @lukaselmer @ClarkYin The issue with hot restart should be fixed in version 0.1.2! You may need to delete your Podfile.lock in order to get the new version of amplify-ios, upon which this change is dependent. If you are unable to pull in the new version of amplify-ios in your Pods, try the suggestion [here](https://github.com/aws-amplify/amplify-flutter/issues/501#issuecomment-823417071).

**Comment by jcowley** [comment]
@haverchuck: Just to note, there are still issues with duplicate calls to `Amplify.configure()` causing an exception, though not the fatal crash caused by #501. The issue is that there is no way to detect whether Amplify has already been configured, and subsequent calls throw an exception that has to be stepped over in the debugger. They added an `isConfigured` attribute (#303) but it does not work (see #412).

The behavior described in this issue is different now because all of the exceptions were refactored in a recent release, but the problem still exists.

**Comment by haverchuck** [comment]
https://github.com/aws-amplify/amplify-flutter/pull/527

**Comment by haverchuck** [comment]
@jcowley We have just released version 0.1.4 and have addressed this.  The isConfigured getter will not work immediately on hot restart (because hot restart destroys dart state), but if you call configure on a hot restart just as you would on an initial app start, we detect in our platform-specific code whether amplify has already been configured, swallow the resulting error that is sent to the dart code via the method channel, re-wire the amplify plugins in dart, and reset the isConfigured value.

**Comment by jcowley** [comment]
Thanks @haverchuck. I'll give it a try.

**Comment by jcowley** [comment]
@haverchuck: It's working for me. Thank you!

**Comment by haverchuck** [comment]
@lukaselmer Is this issue resolved on your end?

**Comment by lukaselmer** [comment]
> The isConfigured getter will not work immediately on hot restart (because hot restart destroys dart state), but if you call configure on a hot restart just as you would on an initial app start, we detect in our platform-specific code whether amplify has already been configured, swallow the resulting error that is sent to the dart code via the method channel, re-wire the amplify plugins in dart, and reset the isConfigured value.

> @lukaselmer Is this issue resolved on your end?

I couldn't test it yet, but this seems to do exactly what I would expect :) thank you!

**Comment by sgehrman** [comment]
Doesn't seem to work for me.  Linux/Android simulator 0.1.5

PlatformException (PlatformException(AmplifyAlreadyConfiguredException, Translating platform exception failed. Please take a look at
https://github.com/aws-amplify/amplify-flutter/issues to see if there are any existing issues that
match your scenario, and file an issue with the details of the bug if there isn't., {recoverySuggestion: Do not add plugins after calling `Amplify.configure()`., message: Amplify has already been configured.}, null))

**Comment by amizer12** [comment]
This started to happen again since update to 0.5 - every hot restart throws the exception - making it impossible to use hot restart - just full stop start only.
Any way i can workaround it ?

**Comment by abdallahshaban557** [comment]
hi @amizer12 - Can you please submit a new [GH issue](https://github.com/aws-amplify/amplify-flutter/issues/new?assignees=&labels=&template=BUG-REPORT.yaml) so that we can properly triage this?

**Comment by abdallahshaban557** [comment]
@amizer12  - thank you for submitting [this GH issue](https://github.com/aws-amplify/amplify-flutter/issues/1658#issuecomment-1143560828). Our team is investigating this now.
