### ISSUE TITLE
S3 Storage: Ability to configure File-Access Level URL Segment

### ISSUE THREAD

**Issue by cody1024d** [aws-amplify/amplify-flutter#1257]
When fetching the URL by a given key, I'd like the ability to ignore or customize the {public,protected,private} portion of the S3 URL. This gets appended automatically, based on the access level, however, there are use-cases where these are customized on the server.

This is currently a feature in Amplify JS [#332](https://docs.amplify.aws/lib/storage/configureaccess/q/platform/js/#customize-object-key-path), but does not seem to have parity across in Android. It looks like this was recently completed in IOS as well: [#916](https://github.com/aws-amplify/amplify-ios/issues/916)

The common workaround in IOS and Android is to fall back to the older TransferUtility code, however this is not possible in Flutter.

Here is the link to a similar issue asking for this request in Android: [#910](https://github.com/aws-amplify/amplify-android/issues/910)

**Comment by Jordan-Nelson** [comment]
Hello @cody1024d - Thank you for taking the time to open the issue and provide references to the docs and feature requests for other amplify libraries. We are currently tracking this request in https://github.com/aws-amplify/amplify-flutter/issues/416. I updated the description to include some of the links you have added here. Please feel free to give that issue a 👍 to express interest in the feature.

Since this looks like it is just waiting on support in Amplify-Android now, I will check to see if this is planned for that library in the near future.

I'm going to close this issue since we are tracking this in #416.

**Comment by cody1024d** [comment]
@Jordan-Nelson Thank you for that link! I'm not sure how I missed that existing request --- my search-foo has failed me :( LOL

I'll definitely give that one a bump though :)
