### ISSUE TITLE
Essential method not implemented yet

### ISSUE THREAD

**Issue by gusdoe** [aws-amplify/amplify-flutter#129]
In cognito, getting Id_token and user_token is essential to make this package useful and valuable. But this part is not even in the developer preview version yet. Should be in high priority of TODOS

**Comment by gusdoe** [comment]
In cognito, getting Id_token and user_token is essential to make this package useful and valuable. But this part is not even in developer preview version yet. Should be in high priority of TODOS.

**Comment by fjnoyp** [comment]
Hi @gusdoe thanks for bringing this issue to our attention.  You should be able to get these tokens via: 

CognitoAuthSession res = await Amplify.Auth.fetchAuthSession(options: CognitoSessionOptions(getAWSCredentials: true));
      FutureOr token = res.userPoolTokens.idToken;

We will update our documentation to make this clearer in the future: 
https://github.com/aws-amplify/docs/pull/2373

**Comment by gusdoe** [comment]
Thank you fjnoyp!

Finding idToken makes it worth to try this for me.

**Comment by droy312** [comment]
await Amplify.Auth.fetchAuthSession(options: CognitoSessionOptions(getAWSCredentials: true)); is returning a value of AuthSession so can't get idToken

**Comment by Jordan-Nelson** [comment]
@droy312 you can safely cast the response to a `CognitoAuthSession`. The response is type `AuthSession` since Amplify is built in a way that would allow for custom implementations. If you are using Cognito, this will be `CognitoAuthSession`.

Here is an example in the docs: https://docs.amplify.aws/lib/auth/access_credentials/q/platform/flutter/
