### ISSUE TITLE
Amplify push not working with flutter when using a REST api?

### ISSUE THREAD

**Issue by lukaselmer** [aws-amplify/amplify-flutter#130]
**Describe the bug**

`amplify push` cannot publish an api when using flutter, it seems

```
Creating API models...
✖ An error occurred when pushing the resources to the cloud

Unsupported framework. flutter
An error occurred during the push operation: Unsupported framework. flutter
```

**Amplify CLI Version**

4.29.4

**To Reproduce**

* install experimental flutter cli
* create s3 storage
* create a python function
* create a rest api to execute the python function
* `amplify push --yes` runs, and in the end fails with the error described above

**Desktop (please complete the following information):**

 - OS: Mac
 - Node Version. v14.4.0

**Comment by lukaselmer** [comment]
@Ashish-Nanda I'm developing an app which consists of a android (flutter) app, some lambda functions, a rest api, and a react frontend for the desktop. I know that the rest api is not available in flutter, but I'd like to use it in the react app, so I'd like to deploy it. How do you suggest I can solve that? In general I'm quite frustrated using amplify, and wish I would have used firebase instead... 🙄 

@haverchuck is it a good idea to close issues which are still open?

**Comment by Ashish-Nanda** [comment]
@lukaselmer Could you let us know what are some of the specific pain points you are facing with Amplify, so that we can work on addressing them and improving the experience further. At this time Amplify Flutter is still in preview, and a lot of additional features and improvements are coming in the upcoming weeks and months.

With regards to deploying a REST API, since you plan to integrate it in a React app as well, you can use the Amplify CLI to add the configuration and create your backend by running the commands in the root folder of your react project itself. Please take a look at the [documentation](https://docs.amplify.aws/lib/restapi/getting-started/q/platform/js) for a detailed walkthrough of the steps required.

Once we add support for the REST API category for Flutter, you can update your `amplifyconfiguration.dart` file to use your existing backend resources to get it working in your Flutter app.
