### ISSUE TITLE
PlatformException(AmplifyException, Failed to Configure Amplify, The operation couldn’t be completed. (Amplify.PluginError error 2.), null)

### ISSUE THREAD

**Issue by tyrone-ligph** [aws-amplify/amplify-flutter#150]
I have setup amplify for flutter. its currently working for Android but for iOS it just fails to configure.
In android I can already use SignIn, SignUp, Signout, etc..
however in iOS, it just logs in this error.

`flutter: PlatformException(AmplifyException, Failed to Configure Amplify, The operation couldn’t be completed. (Amplify.PluginError error 2.), null)
`

**To Reproduce**
Just configure AWS Amplify for Flutter like in the docs.

**Expected behavior**
It should work for iOS

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in (check all that apply):
[] Android
[✓] iOS

**Smartphone (please complete the following information):**
 - Device: iPhone8 simulator

**Comment by haverchuck** [comment]
Hi @tyrone-ligph -  Which ios platform version are you using, and which amplify-flutter plugins are you adding?

**Comment by Ashish-Nanda** [comment]
Hi @tyrone-ligph were you able to get this working?

**Comment by ibadaboom** [comment]
Would be nice, if you post a solution instead of just closing it.

**Comment by jamesonwilliams** [comment]
Hi @ibadaboom! Even as authors, we often don't have a complete understanding of the software. This is, in its essence, the nature of bugs. In order to reproduce issues, and while also working on other responsibilities, we need a solid set of repro steps. You can help us by providing more information as @Ashish-Nanda & @haverchuck have requested. Thank you!

**Comment by ibadaboom** [comment]
I'm trying to use an existing configuration of the user pool. More information I can't give you too, because the stacktrace of the error is null. Are all the informations in amplifyconfiguration.dart needed for your plugin to work? For now, I just used https://pub.dev/packages/flutter_aws_amplify_cognito plugin, which worked without any more information, then printed below:

`{
    "IdentityManager":
    {
        "Default": {}
    },
    "CognitoUserPool":
    {
        "Default":
        {
            "PoolId": "eu-central-1_xxxxxxxxxxxx",
            "AppClientId": "xxxxxxxxxxxxxxxxxxxxxx",
            "Region": "eu-central-1"
        },
    }
}`

So I tried to adapt it for the amplifyconfiguration.dart 
`const amplifyconfig = ''' 
{
  "UserAgent": "aws-amplify-cli/2.0",
  "Version": "1.0",
  "auth": {
      "plugins": {
          "awsCognitoAuthPlugin": {
              "IdentityManager": {
                  "Default": {}
              },
              "CognitoUserPool": {
                  "Default": {
                      "PoolId": "eu-central-1_xxxxxxxxxxx",
                      "AppClientId": "xxxxxxxxxxxxxxxxxx",
                      "Region": "eu-central-1",
                  }
              },
          }
      }
  }
}''';`

And here is how I initialize it.
` final Amplify amplifyInstance = Amplify();
  final AmplifyAuthCognito auth = AmplifyAuthCognito();

  Future<bool> configureAmplify() async {

    // Add Cognito Plugins
    try {
      await amplifyInstance.addPlugin(authPlugins: [auth]);
    } catch (e) {
      print(e);
    }
    
    // Once Plugins are added, configure Amplify
    try {
      await amplifyInstance.configure(amplifyconfig);   //<- here the error happens
    } catch (e) {
      print(e);
    }
    
    listenForAuthEvents();
    return true;
  }`
