### ISSUE TITLE
Can't do an archive/release build because of module amplify_auth_cognito

### ISSUE THREAD

**Issue by horgag** [aws-amplify/amplify-flutter#151]
**Describe the bug**
Trying to do a release build. Fails to build because `Module 'amplify_auth_cognito' not found` in the GeneratedPluginRegistrant.m file

**To Reproduce**
run `flutter build iOS`
Initially you might a get build fail with `Please specify a platform for this target in your Podfile`

This can be resolved by uncommenting this line in your Podfile `# platform :ios, '9.0'`

I changed mine to `iOS 12`;

Run  `flutter build iOS` again  Error:

```
/Users/ger/projects/Rio/ios/Runner/GeneratedPluginRegistrant.m:16:9: fatal error: module 'amplify_auth_cognito' not found
    @import amplify_auth_cognito;
     ~~~~~~~^~~~~~~~~~~~~~~~~~~~
    1 error generated.

```

**Expected behavior**
Build releases successfully 

**Screenshots**
<img width="849" alt="Screenshot 2020-10-12 at 11 58 57" src="https://user-images.githubusercontent.com/1724108/95739180-54a03780-0c82-11eb-8510-ebc5f5ef3f38.png">

**Platform**

[] iOS

**Smartphone (please complete the following information):**
 

**Additional context**
This is happening on two different machines ...And is preventing us to get on TestFlight

**Comment by horgag** [comment]
I've also tried to do a release build with your sample app. And I've got the same error. Please let me know what you think.
<img width="667" alt="Screenshot 2020-10-12 at 15 12 43" src="https://user-images.githubusercontent.com/1724108/95756408-a904e080-0c9d-11eb-8cc7-8926bab1ddf0.png">

**Comment by Ashish-Nanda** [comment]
Hi @horgag thanks for reporting this, we'll look into creating a release build to try and root cause the problem.

I saw you also created https://github.com/aws-amplify/amplify-flutter/issues/147

Is that still an issue for you, or were you able to resolve it?

**Comment by horgag** [comment]
Thanks for you speedy response! I'll close #147 but it might be related.

**Comment by haverchuck** [comment]
@horgag I think this is a documentation miss on our part, which we will work to correct ASAP. The issue is that, as you have probably guessed, certain minimum platform versions are required for certain categories.  I was able to reproduce this issue locally, and solved it by:

1. Changing the `platform :ios `value in the Podfile to at least `11` (which you've done)
2. Similarly changing the deployment target in XCode under Project "Runner" -> Info Tab -> Deployment Target
![image](https://user-images.githubusercontent.com/10621276/95778866-d2ae0f80-0c7d-11eb-9ce0-f2ef0d8ad391.png)

After these steps, 'flutter build ios' succeeds.  Does this help you?

**Comment by horgag** [comment]
@haverchuck thanks for getting back so quickly and giving a solution which works. I'm now able to build in release mode. I'm closing the issue. Cheers.

**Comment by manjunathpm** [comment]
I am facing same issue on android.

`FAILURE: Build failed with an exception.

* What went wrong:
Task 'assembleAarRelease' not found in root project 'amplify_auth_cognito'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s

The plugin amplify_auth_cognito could not be built due to the issue above.
Process finished with exit code 1`

can someone please help.?

**Comment by MohammedShehata** [comment]
@horgag did you figure out a solution for your issue?

**Comment by horgag** [comment]
@MohammedShehata  yes the above solution given by haverchuck
