### ISSUE TITLE
[HELP] how to get userSub after signedUp?

### ISSUE THREAD

**Issue by vuchau** [aws-amplify/amplify-flutter#180]
Hi,
 I need get userSub after signup to create new user profile on database, but I can't see any properties to do it

```
Future<SignUpResult> signUp(String username, String password,
      Map<String, dynamic> userAttributes) async {
    try {
      final signupResult = await Amplify.Auth.signUp(
          username: username,
          password: password,
          options: CognitoSignUpOptions(userAttributes: userAttributes));
      return signupResult;
    } catch (e) {
      throw e;
    }
  }
```

**Platform**
[x] Android
[] iOS

**Smartphone**
 - Device: Pixel 2
 - OS:  Android 9

Pubspec.yaml dependencies only contains:
amplify_core: ^0.0.1-dev.3
amplify_auth_cognito: ^0.0.1-dev.3

**Comment by haverchuck** [comment]
@vuchau I've added this as a feature request that will be discussed.  For the time being, have you looked into using Cognito Lambda Triggers?  To be clear, I can't remember off the top of my head if the userSub is available in the trigger, but I suspect that it is.  This might actually be a good option for your use case regardless of whether this feature request gets built.

**Comment by vuchau** [comment]
> @vuchau I've added this as a feature request that will be discussed. For the time being, have you looked into using Cognito Lambda Triggers? To be clear, I can't remember off the top of my head if the userSub is available in the trigger, but I suspect that it is. This might actually be a good option for your use case regardless of whether this feature request gets built.

I haven't used Cognito Lambda Trigger for this yet, I have looked through the Pre Sign-up Lambda Trigger but still can't see the userSub (userId) attribute.
My data flow as below:
When the user registers to the system, I will create a user profile with the primary key is **userSub** (userId) from Cognito and the status **INACTIVE** and will switch to **ACTIVE** after the user has confirmed the code received from the email (phone number).

Thanks,

**Comment by haverchuck** [comment]
@vuchau You could explore using a[ CustomMessage](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-custom-message.html) trigger in this scenario.  This trigger is called when confirmation or MFA messages are dispatched, and thus are called immediately after signUp but before user confirmation.  You can create these with the Amplify CLI.

To demonstrate, I created the following trigger code:

```
exports.handler = (event, context, callback) => {
  console.log('event', event);
  callback(null, event);
};
```
After the trigger is called, I checked CloudWatch and saw the following output for `console.log('event', event)`:
```
event { 
  version: '1',  
  region: 'us-west-2',  
  userPoolId: 'us-west-2_<myup>,  
  userName: 'triggerdemo',  
  callerContext:   { 
    awsSdkVersion: 'aws-sdk-unknown-unknown',     
    clientId: 'myid' 
   },  
   triggerSource: 'CustomMessage_SignUp', 
   request:   { 
     userAttributes:  { 
       sub: 'my-newly-created-usersub',
   ....more json....
   }
}
      
```
As you can see, the usersub is available here. 

We can explore a better fix on our side, of course, but for the time being I thought this might assist you.

**Comment by WathikAhmed** [comment]
Question: 
Is `userSub` like a permanent user ID for the users? Because on the Amplify Admin UI it says `Unique identifier (username)` which means it is regarding the username as the ID for the user? Im looking for something a little more distinguishable because the users may want to change their username in the future and so a separate ID would be a lot more reliable.

**Comment by Jordan-Nelson** [comment]
@WathikAhmed - userSub will not be reassigned. See https://forums.aws.amazon.com/thread.jspa?threadID=243796 for a similar question/answer.

@vuchau - An auth trigger is definitely the way I would recommend achieving the functionality you are looking for. Creating a user in a database is a great example of what an auth trigger can be used for actually. Having this run in an auth trigger has the benefit of being more reliable than trying to run it from the client. Implementing this on the client could lead to issues where the sign up completes, but the record in the DB does not get created (because the client loses network connection, for example).

Did you have any trouble achieving this in an auth trigger, or do you see any other use case for accessing the sub immediately after sign up? If not, I am going to close this out.

**Comment by WathikAhmed** [comment]
@Jordan-Nelson Thanks for the answer and the link to the forum 👍

**Comment by Jordan-Nelson** [comment]
Closing this out. If you feel like there is a use case for this, please feel free to open another issue.
