### ISSUE TITLE
how to login using facebook , Google  , Twitter ?

### ISSUE THREAD

**Issue by KaliTHB** [aws-amplify/amplify-flutter#182]
i want to login using identity pools

**Comment by haverchuck** [comment]
@KaliTHB - We plan to support an OAuth flow with Cognito Hosted UI (User Pools) soon, but we do not currently have identity pool federation planned. I'll mark this as a feature request.

**Comment by fryette** [comment]
Must have feature, will wait...

**Comment by cnttechio** [comment]
I'm waitting this feature.

**Comment by rish07** [comment]
Hey @haverchuck, is anyone working on this feature request? I would like to contribute by adding this feature. I am an MLH fellow.

**Comment by jcblancomartinez** [comment]
> @KaliTHB - We plan to support an OAuth flow with Cognito Hosted UI (User Pools) soon, but we do not currently have identity pool federation planned. I'll mark this as a feature request.

Hi,
I'm interested in enabling external federated identity providers (i.e. Google, Facebook) in Cognito's user pool with Flutter. I would like the flexibility to own the UI to support multiple languages. Is there any issue I can track or you recommend me creating one?

Thanks.

**Comment by Dedecube** [comment]
I'm waiting this feature too. Now I'm using other library that isn't supported anymore. I want to add Google, Facebook, ... sign in with my own UI. Please let we know any plan about this feature request.

**Comment by bjoern-from-kopply** [comment]
Sign in with Apple and Google would be very much appreciated and it's critical as it increases user signup dramatically.
Would also prefer an own UI and use the ``Auth. federatedSignIn`` command to login.

**Comment by TseWong1** [comment]
Hi Everyone, My flutter app is already authenticated using google sign-in/firebase Auth.  I would like to know if there is a way to pass the certificate/Token to Cognito/Single Sign On to access AWS backend resources (API GW, Lambda, S3 and Dynamo).

Many thanks,

Tse

**Comment by durannumit** [comment]
Any update? I'm waiting for Sign in with Apple and Google.

**Comment by dondragon2** [comment]
Any updated on authentication with identity pool federation?

**Comment by BerndWessels** [comment]
I believe this whole cognito user pools and federated identities signup situation is extremely limited by the currently exposed SDK.

See this for details [medium article](https://medium.com/@wesselsbernd/some-aws-cognito-appsync-details-as-of-may-2019-247c8531f600)

@haverchuck 
Please AWS address this, otherwise we cannot use Amplify and AppSync at all for apps targeting a "social" audience :( Without google and facebook login we are losing 99% of our market, therefore this is a showstopper for Amplify.

**Comment by haverchuck** [comment]
@KaliTHB @fryette @cnttechio @rish07 @jcblancomartinez @Dedecube @BerndWessels @dondragon2 @durannumit @TseWong1 @bjoern-from-kopply 

We've just released support for [Cognito Hosted UI!](https://docs.amplify.aws/lib/auth/signin_web_ui/q/platform/flutter)

That being said, I think there are a couple different feature requests described in this issue. If your use case is not met by this feature, please log a different issue.

**Comment by matthewfx** [comment]
Hey AWS team. Could you please let us know if and when we can expect this to be done? It is a weird experience that Google/Apple sign-in has to be done through a web UI and we've been experiencing drop-offs because of it. I think that should be very high on your priority list. Thank you in advance for any updates on it.

**Comment by matthewfx** [comment]
@haverchuck Could you please tell us when we can expect you delivering it? We've been experiencing quite a lot of drop offs and the fact that Google started randomly asking users to verify if it is them by sending notifications to their YouTube app has been making things even worse. I'm sorry that I keep pushing on it but Amplify is not a free service and you shouldn't make your clients waiting this long for such important features. Not only that but this particular one is available on your other platforms SDKs so you don't need to create it from a scratch...

**Comment by padaszewski** [comment]
@matthewfx could You manage to find any workaround for this issue by now?

**Comment by flodaniel** [comment]
@dnys1 tagging you, as you have been very responsive and helpful in the past. Is this feature request something you guys have on the roadmap? Maybe planned for the rewrite that is happening with the current developer preview? 

I would love to see a signInWithCredentials feature, that not even requires identity pools, but we 100% understand if that is something that is a decision by the cognito team.

**Comment by romk1n** [comment]
When is federated login coming to flutter? is there an ETA ?

**Comment by dnys1** [comment]
The new [`federateToIdentityPool`](https://pub.dev/documentation/amplify_auth_cognito_dart/latest/amplify_auth_cognito_dart/AmplifyAuthCognitoDart/federateToIdentityPool.html) API allows federating directly into an identity pool now using a third-party OIDC token. This is available in v1.0.0 of the Amplify libraries using the registered Cognito plugin and gives you access to authenticated AWS credentials.

```dart
Future<AWSCredentials> federateWithGoogle() async {
  const provider = AuthProvider.google;
  const token = '...';
  final plugin = Amplify.Auth.getPlugin(AmplifyAuthCognito.pluginKey);
  final session = await plugin.federateToIdentityPool(
    token: token,
    provider: provider,
  );
  return session.credentials;
}
```

See the [Cognito docs](https://docs.aws.amazon.com/cognito/latest/developerguide/external-identity-providers.html) for more information on configuring this in your identity pool. **Note** that this does not solve the problem of federating into a user pool without Hosted UI. In order to login, you'll still need to use Hosted UI.

**Comment by padaszewski** [comment]
@dnys1 
I think it is premature to close this issue. One main goal here is to have the native integration of login pop-up screens without the use of hosted UI, which provides terrible user experience.
[This](https://github.com/aws-amplify/amplify-flutter/issues/438) was closed, because the progress should be tracked here. I vote to re-open this.

**Comment by dnys1** [comment]
Since this issue was originally about identity pool federation, I think it makes sense to close it. I've reopened #438 to track federation into user pools. Thanks for letting me know.
