### ISSUE TITLE
Support for UpdateUserAttributes operation

### ISSUE THREAD

**Issue by jcblancomartinez** [aws-amplify/amplify-flutter#193]
Hi,

Support to invoke UpdateUserAttributes operation.

https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_UpdateUserAttributes.html

Thanks.

Regards.

**Comment by jamesonwilliams** [comment]
This functionality will be added soon. This issue should be marked as a feature request.

The other platforms have an `updateUserAttributes(...)` method. There is [a placeholder for this functionality in the Amplify Flutter documentation](https://docs.amplify.aws/lib/auth/user-attributes/q/platform/flutter#update-user-attribute).

**Comment by Jordan-Nelson** [comment]
Hi @jcblancomartinez - I just wanted to provide an update that `updateUserAttribute` was added in 0.1.5. Support for updating multiple user attributes at once has not yet been added though so I will keep this issue open. [Here are the docs](https://docs.amplify.aws/lib/auth/user-attributes/q/platform/flutter#update-user-attribute) on the functionality added in 0.1.5.

**Comment by Jordan-Nelson** [comment]
Noting that there is currently a bug with `updateUserAttributes` on Android that will probably require a fix prior to this being implemented in Flutter. The success callback is called multiple times, which results in a fatal exception from the flutter engine due to the success callback on the method channel being invoked multiple times. Issue for reference: https://github.com/aws-amplify/amplify-android/issues/1263

**Comment by haverchuck** [comment]
@jcblancomartinez This has been included in version 0.1.6! We will leave this issue open for a while for comment.

**Comment by Jordan-Nelson** [comment]
Closing issue as the feature has been added as of amplify-flutter 0.1.6
