### ISSUE TITLE
[RFC]: API Category Changes

### ISSUE THREAD

**Issue by ragingsquirrel3** [aws-amplify/amplify-flutter#2035]
_This is a Request For Comments (RFC). RFCs are intended to elicit feedback regarding a proposed change to the Amplify Framework. Please feel free to post comments or questions here._

This RFC is to gather customer feedback for a new proposed functionality in amplify-flutter related to the API category (REST and GraphQL) and we would like to hear from Amplify customers how these changes might impact you or if there are other changes you might suggest.

Please comment with your feedback such as:

* How and which particular changes might be helpful to you?
* Which changes would you like to avoid and why?
* What are you current paint points when working with the API category? Are they not posted here?

## 1. Summary

The current implementation of amplify-flutter is based on method channels and the amplify-android/ios implementations. amplify-flutter is investigating a dart implementation of the API category to better support Flutter platforms beyond Android and iOS. While adding wider platform support, it may also become easier to add some missing features or otherwise change functionality because implementation is no longer bound to amplify-ios or amplify-android. In doing so, it may make sense to change some of the public API.

For both GraphQL and REST operations, use [CancelableOperation](https://pub.dev/documentation/async/latest/async/CancelableOperation-class.html) instead of custom `GraphQLOperation` and `RestOperation`. For REST methods, breaking changes are proposed to improve encoding and decoding of requests and responses in addition to improving flexibility with streaming responses. In GraphQL, add support for an optional authorization mode parameter and custom HTTP headers.

## 2. Rationale

The  `CancelableOperation` from the async package is more likely to be compatible with other plugins in the Flutter ecosystem and reduce maintenance/duplication. The improvements to REST methods are meant to simplify encoding and decoding of requests and responses, especially with the common case of sending a request with a JSON body.

## 3. Proposed Changes

1. deprecate `GraphQLOperation` and `RestOperation`. Instead use the standard dart async [CancelableOperation](https://pub.dev/documentation/async/latest/async/CancelableOperation-class.html) where value resolves to either `GraphQLResponse` or a streaming HTTP response ( `CancelableOperation<GraphQLResponse>` and `CancelableOperation<AWSStreamedHttpResponse>`). In summary, developers will call `operation.value` instead of `operation.response`.
2. deprecate many classes related to REST API, including `RestOperation`, `RestResponse`, `RestOptions`. and `RestException`. The information will instead be represented using named parameters. In summary, Amplify REST methods have a similar signature to those of [high-level dart HTTP convenience methods](https://pub.dev/documentation/http/latest/http/http-library.html#functions) .get(), .post(), etc... with a few differences (summarized here with revised signatures and code examples below):
    a. The returned response is now a type of `AWSStreamedHttpResponse` to give callers the flexibility to stream the response body rather than converting to a string all at once.
    b. For HTTP request methods with a body, the body is of type `HttpPayload` which has factory constructors such as `HttpPayload.json(Object body, {Encoding encoding = utf8})` or `HttpPayload.string(String body, {Encoding encoding = utf8})` so that callers no longer have to encode request bodies manually. See example usage below for the common case of a JSON body from a map in dart.
4. deprecate `Amplify.API.cancelRequest()` method in favor of `CancelableOperation` `.cancel()` method, which requires access to the operation from the original method. This is currently only available for GraphQL requests provided the caller keeps track of the request ID. The benefit is that the plugin code no longer has to maintain a collection of in-flight requests, reducing possibility of memory leaks and complexity. 
5. Do not raise `RestException` when the status code of a response is not in the success range. Simply return the response and let the caller determine error behavior based on the response itself. Exceptions will only be raised for client-side errors where a request cannot be sent. Server-side logic will not throw an exception.
6. Make errors nullable in `GraphQLResponse` to better reflect the GraphQL spec.
7. `GraphQLRequest` has additional optional enum property `authorizationMode` ([like Amplify JS](https://github.com/aws-amplify/amplify-js/blob/84c94fd0efda11c27bb39a0bf2421e99b52ae612/packages/api-graphql/src/types/index.ts#L21)) which the caller can use to specify the auth mode when the backend has multiple authorization modes.
8. Add an optional headers property of type `Map<String, String>?` to `GraphQLRequest` to support custom HTTP headers.
9. Support further customization of HTTP logic by allowing an optional definition of an HTTP client similar to HTTP’s [BaseClient](https://pub.dev/documentation/http/latest/http/BaseClient-class.html). This would be an optional parameter named `baseHttpClient` supplied once when instantiating the plugin. If supplied, that client definition would be used for all HTTP requests from the plugin. For example, a caller could write a client with custom retry logic so that all Amplify API HTTP methods (REST or GraphQL query/mutate) would follow that retry logic.

## 4. Code Samples

REST usage:

```dart
// current
RestOperation restOperation = Amplify.API.post(
  restOptions: RestOptions(
    path: 'items',
    body: ascii.encode('{"name":"Mow the lawn"}'),
  ),
);
RestResponse response = await restOperation.response;
print(response.body);

// revised
CancelableOperation<AWSStreamedHttpResponse> operation =
  Amplify.API.post(
    'items',
    body: HttpPayload.json({'name': 'Mow the lawn'}),
  );
AWSStreamedHttpResponse streamedResponse = await restOperation.value;
String body = await streamedResponse.decodeBody(); // streamed body
print(body);

// or get the body all at once
AWSHttpResponse response = await restOperation.response;
print(response.decodeBody());
```

GraphQL usage (same for  .query() and .mutate()):

```dart
// current
GraphQLResponse<Blog> gqlRes = await Amplify.API.query(request: someRequest).response;
// revised, only change .response to .value on operation in simple example
GraphQLResponse<Blog> gqlRes = await Amplify.API.query(request: someRequest).value;
```

For GraphQL subscriptions, there would be no breaking changes.

## 5.  Revised REST method signatures

For methods with no body (GET and HEAD):

```dart
CancelableOperation<AWSStreamedHttpResponse> get(
    String path, {
    Map<String, String>? headers,
    Map<String, String>? queryParameters,
    String? apiName,
}) {...}
```

For methods with a body (DELETE, PATCH, PUT, POST):

```dart
CancelableOperation<AWSStreamedHttpResponse> post(
    String path, {
    HttpPayload? body,
    Map<String, String>? headers,
    Map<String, String>? queryParameters,
    String? apiName,
}) {...}
```

## 6. Drawbacks

Breaking changes, especially for REST methods. Smaller changes for GraphQL.

## 7. Alternatives

1. In REST, rather than returning streamed responses via `AWSStreamedHttpResponse`, return a non-streamed `AWSHttpResponse`   or a [Response](https://pub.dev/documentation/http/latest/http/Response-class.html) from the dart http package.
2. Cancellation API based on cancel tokens, like [this dio example](https://github.com/flutterchina/dio#cancellation).

### Categories

- [ ] Analytics
- [X] API (REST)
- [X] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Storage

**Comment by vgribok** [comment]
### re: CancellableOperation

Enthusiastic yes to the CancellableOperation, or better yet, to a variant that takes a cancellation token. The advantage of the cancellation token is that it can cancel multiple operations, unlike multiple CancellableOperations that need to be cancelled one after another. If Dio is taken as an inspiration, please stay with the async/await flow rather than with the builder/fluent `.then().onError()`. 

### re: Deprecating the RestException

Please keep an exception instead of returning an HTTP code for the caller to process. Returning a code rather than throwing an exception will force the antipattern of boilerplate error handling each call like in old C programs. Throwing an exception allows callers higher on the stack to have a catch-all exception handler.
I understand where you are coming from when you consider the option of returning an HTTP code: non-200 results are much more common than, say, memory exceptions. Still, it took us a good decade to arrive at the async/await with proper exception handling code style, so please let's retain it. To simplify handling those non-error-yet-not-success HTTP return codes, please consider using centralized/singleton HTTP code handlers via a factory or a DI/IoC and throw an exception if a handler is not present.

### re: AWSStreamedHttpResponse vs alternatives

Please clarify whether `AWSStreamedHttpResponse` will have both `streamedResponse` and `response` futures returning non-buffered/chunked and buffered/complete responses respectively. If so, the AWSStreamedHttpResponse should work well as long as it's possible to tell streamed and complete responses apart. A definition of the AWSStreamedHttpResponse API would be helpful. 

### Miscellaneous

- CancellableOperation seems like it can't be subclassed due to it having a single private constructor. To make a response body an accessor of the [valueOrCancellation](https://pub.dev/documentation/async/latest/async/CancelableOperation/valueOrCancellation.html) property, some clever tricks may be required.
- Sample snippet would be more expressive and easier to get its intent if explicit types were used in places like `final response = await restOperation.response;`.

**Comment by dnys1** [comment]
>  a variant that takes a cancellation token

Part of the discussion around this was the lack of interoperability between cancellation tokens. If we vended our own token type, it would only work with AWS/Amplify types, and there isn't one we can pull from the std library/Dart team packages. But maybe this is less of an issue if it's coupled with CancelableOperation, which is a std type.

> Returning a code rather than throwing an exception will force the antipattern of boilerplate error handling each call like in old C programs.

I can see the argument for this, but it seems like it should be an individual's decision rather than the default since HTTP codes inherently have no semantic meaning. A 404 might be just as expected as a 200 for certain HTTP calls and needing to have two distinct code paths to handle these is just as cumbersome IMO.

The idea is to allow users to pass in a custom HTTP client which would easily allow defining a client which threw exceptions for all non-2xx status codes.

> Please clarify whether AWSStreamedHttpResponse will have both streamedResponse and response futures.

Yes, instead of a synchronous `body` property, there are two async properties for accessing the body of a response, plus a third helper method to decode the body as a String. In all cases, though, the response stream is only listened on when requested. [Full definition](https://github.com/aws-amplify/amplify-flutter/blob/ae71dd5ba31132673d1c4fc65a98baf76f164259/packages/aws_common/lib/src/http/aws_http_response.dart#L83).

```dart
class AWSStreamedHttpResponse {
  /// The response's body.
  Stream<List<int>> get body;

  /// The collected bytes of the response [body].
  Future<List<int>> get bodyBytes;

  /// Decodes the response body using [encoding] (defaults to UTF-8).
  Future<String> decodeBody({Encoding encoding = utf8});
}
```

> CancellableOperation seems like it can't be subclassed due to it having a single private constructor. To make a response body an accessor of the [valueOrCancellation](https://pub.dev/documentation/async/latest/async/CancelableOperation/valueOrCancellation.html) property, some clever tricks may be required.

We are suggesting only using the `value` property, although you could use `valueOrCancellation` fairly easily, I think:

```dart
final AWSStreamedHttpResponse? response = await operation.valueOrCancellation();
if (response != null) {
  final String body = await response.decodeBody();
  print(body);
}
```

> Sample snippet would be more expressive and easier to get its intent if explicit types were used in places like `final response = await restOperation.response;`.

Agreed. @ragingsquirrel3 can we update to include types in the snippets?

**Comment by ragingsquirrel3** [comment]
updated the snippets, thanks again Vlad!

**Comment by vgribok** [comment]
Thank you Travis, Dillon.

Here are a few more clarifications of my points.

### CancelableOperation and CancellationToken
I think surfacing [CancelableOperation](https://pub.dev/documentation/async/latest/async/CancelableOperation-class.html) at a high-abstraction-level API like Amplify is treacherous due to:
1. It has `value` property that lots of new developers will go for, while they would need to use [valueOrCancellation()](https://pub.dev/documentation/async/latest/async/CancelableOperation/valueOrCancellation.html) method instead. This will be too error-prone to be practical, IMO.
2. CancelableOperation class is sealed, significantly restricting options of adding and altering functionality.
3. To address Dillon's interoperability concerns, I have taken a stab at defining a [CancellationToken](https://gist.github.com/vgribok/3ead554151cdf11d2c91ff0b6530dd99#file-dart-L27) class [friendly to Future](https://gist.github.com/vgribok/3ead554151cdf11d2c91ff0b6530dd99#file-dart-L68) and to [CancelableOperation](https://gist.github.com/vgribok/3ead554151cdf11d2c91ff0b6530dd99#file-dart-L72). Please see whether it may alleviate interoperability issues. Dillon has floated the idea of surfacing CancellationToken at the Amplify (high-level) API, and rely on CancelableOperation in lower-level SDK APIs - I think this is a great way to approach it.

### Exceptions vs returning HTTP codes
With full appreciation of the fact that HTTP codes could mean different severity for different use cases, I think that the best approach is to have highest-level, request-sending APIs throw exceptions rather than returning codes, but allow supplying a centralized/singleton default lower-level handler of http codes that will determine which codes are success, which are errors worth throwing an exception for, and which are transient states that fit cross-cutting concern pattern and can be dealt with once rather than after each API call.

### Streamed vs Non-Streamed response
If REST caller ends up returning `AWSBaseHttpResponse`, which in turn will have the flag indicating whether response body is complete or streamed - that would be alright with me, but I still think having a single response class that has accessors to both streamed and complete response body matches server behavior slightly better. Not a deal-breaker either way, as long as the type of the return can be checked at the run time instead of assuming the type at the design time.
