### ISSUE TITLE
Hi we have multiple sign in url Google login 

### ISSUE THREAD

**Issue by saswat-pcode** [aws-amplify/amplify-flutter#2082]
Hi we have multiple sign in url.
<img width="701" alt="Screenshot 2022-09-01 at 11 04 18 AM" src="https://user-images.githubusercontent.com/110592349/187842002-4ba73951-ea67-42dd-a23d-d0611c3dba82.png">

when i am trying with google login it is through the error 

https://imgur.com/a/BqMN46f

AWS config file

https://imgur.com/eCTPXmn

Android manifest file

https://imgur.com/I8VxRoi

How to resolve this issue ?
For single url that is working.

_Originally posted by @saswat-pcode in https://github.com/aws-amplify/amplify-flutter/issues/2013#issuecomment-1233787220_

**Comment by haverchuck** [comment]
@saswat-pcode Which version of amplify-flutter are you using, and what is the error you're receiving?

**Comment by saswat-pcode** [comment]
https://imgur.com/a/BqMN46f is the exception.

I am using the latest stable version

  amplify_auth_cognito: ^0.6.6
  amplify_flutter: ^0.6.6

**Comment by saswat-pcode** [comment]
Any resolution for this ?

**Comment by dnys1** [comment]
Hi @saswat-pcode, currently the `0.x` versions of Amplify do not support having multiple redirect URIs due to underlying limitations in the iOS/Android SDKs. If your app does not need production-ready libraries for a few months, you can check out the dev-preview version of our Auth category which is written in Dart and allows configuring multiple URIs: 
- https://docs.amplify.aws/lib/project-setup/create-application/q/platform/flutter/#2-install-amplify-libraries
- https://pub.dev/packages/amplify_auth_cognito/versions/1.0.0-next.0+4

**Comment by dnys1** [comment]
Closing this for now as we will not be addressing it in the current `0.x` Amplify versions.

**Comment by saswat-pcode** [comment]
@dnys1 Please reply how could we use multiple URIs in the latest version .

**Comment by dnys1** [comment]
It should work just like you have it. The important thing is that both values are listed in the `SignInRedirectURI` and `SignOutRedirectURI` entries, separated by a comma. Please let me know if this doesn't work for you on the latest versions.
