### ISSUE TITLE
Cognito actions (feature request)

### ISSUE THREAD

**Issue by dev-akshat** [aws-amplify/amplify-flutter#2264]
How to use [Cognito actions](https://docs.aws.amazon.com/pdfs/cognito-user-identity-pools/latest/APIReference/cognito-user-identity-pools-apiref.pdf#API_Operations) like AdminCreateUser or AdminDeleteUser ? (with or without amplify)

Problem Statement:
We want to make a flutter web admin portal for creating, deleting and listing users. As per current docs we can't come up with any way of doing it.  Below are the links of was cognito actions that we need to use. 

https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_Operations.html
https://docs.aws.amazon.com/pdfs/cognito-user-identity-pools/latest/APIReference/cognito-user-identity-pools-apiref.pdf#API_Operations

Please guide us to docs if there is a way of doing it or  consider this a feature request.

**Comment by dnys1** [comment]
Hi @dev-akshat, typically these methods would be called from your backend since they require admin credentials. Amplify supports calling serverless Lambdas through the [Functions](https://docs.amplify.aws/cli/function/) category which can be called at any time. Cognito also supports [Lambda triggers](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-identity-pools-working-with-aws-lambda-triggers.html) which are serverless functions called by Cognito at specific points in the user flow.

You can see some examples of how to call Admin APIs from Lambdas in our integration test backend: https://github.com/aws-amplify/amplify-flutter/tree/next/packages/auth/amplify_auth_cognito/example/backend/lib

**Comment by Jordan-Nelson** [comment]
@dev-akshat - Please let us know if you have any follow up questions. Please note that this currently not supported in dart. The examples linked are in TS/JS. If you are specifically looking to do this in Dart we can either convert this to a feature request or open a new issue to track it.

Note: I believe the dir that @dnys1 linked above has been moved here: https://github.com/aws-amplify/amplify-flutter/tree/next/infra/lib/auth

**Comment by Jordan-Nelson** [comment]
Closing issue since we have not heard back. Please open a new issue if you have any follow up questions. Thanks.
