### ISSUE TITLE
Apple login throwwing error while sign in with apple

### ISSUE THREAD

**Issue by Sunsiha** [aws-amplify/amplify-flutter#2317]
```
2022-11-04 10:44:13.012782+0530 Runner[99290:1494585] [AuthErrorHandler] The operation couldn’t be completed. (Amplify.AuthError error 1.)
```
Plugins:

```
 amplify_flutter: ^0.6.6
 amplify_auth_cognito: ^0.6.6
```
Flutter version:

```
Flutter 3.3.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 4f9d92fbbd (8 weeks ago) • 2022-09-06 17:54:53 -0700
Engine • revision 3efdf03e73
Tools • Dart 2.18.0 • DevTools 2.15.0
```

It was working before. Google and facebook is working.

**Comment by dnys1** [comment]
Hi @Sunsiha - sorry you are facing this issue. In order to investigate it, I'll need a bit more info.

- Can you tell where in the code the error is being thrown? Is it before the sign-in popup is shown? Afterwards?
- Does it happen every time you sign in or just sporadically?
- Is this happening on an iOS simulator, real device, or both?
- Does it happen if you delete and reinstall the app?

Thanks for your patience!

**Comment by Jordan-Nelson** [comment]
Hi @Sunsiha - If you are still facing this issue, can you please provide the info request above. Thanks.

**Comment by HuiSF** [comment]
Hi @Sunsiha please feel free to reopen this issue if you are still experiencing it, we will be happy to help!
