### ISSUE TITLE
Change Hub Events from Strings to Enums

### ISSUE THREAD

**Issue by Lorenzohidalgo** [aws-amplify/amplify-flutter#2349]
Hi there!

@Jordan-Nelson,  Regarding your comment on #1107. If the task of turning the Auth Events from `Strings` to `Enums` is still open / on the roadmap, I could give it a try. This task could also "standardize" the Hub Events by also updating the DataStore Events to be enums.

P.S.: I spoke with @salihgueler and he recommended opening a second issue since documenting the events and applying the changes are two separate tasks.

**Comment by Jordan-Nelson** [comment]
Hi @Lorenzohidalgo - thanks for opening the issue. In the current dev-preview branch we have replaced eventName with type on the AuthHubEvent class. Type is an enum. You can see that update below.

https://github.com/aws-amplify/amplify-flutter/blob/next/packages/amplify_core/lib/src/types/auth/hub/auth_hub_event.dart

We held off on making the same change in the current stable version since it would be breaking. We could add type without removing eventName to make it none breaking, but we are encouraging customers to try out the developer-preview version as it will replace the current stable version.

**Comment by Lorenzohidalgo** [comment]
Thanks for the info @Jordan-Nelson!
