### ISSUE TITLE
Analytics custom events are taking ~1 hour to be registered in the Analytics console filters

### ISSUE THREAD

**Issue by jamilsaadeh97** [aws-amplify/amplify-flutter#2903]
### Description

There's an issue when recording custom events in a Flutter application.
I am using this piece of code:

```dart
final event = AnalyticsEvent("Custom Event");
event.customProperties..addStringProperty("Key0", "Value0")..addIntProperty("Key1", 1);
await Amplify.Analytics.recordEvent(event: event);
await Amplify.Analytics.flushEvents();
``` 

    
It takes approximately 1 hour for this event to appear in the Filter section of the Analytics console.
Also the custom attributes appear one by one in a random time interval (2-10mins).

I want to add that the event count is updated almost immediately. 

### Categories

- [X] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Storage

### Steps to Reproduce

1.Record a custom analytics event in flutter.
2.Go to the console and wait for the event to appear in the filters

### Platforms

- [X] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.7.7

### Amplify Flutter Version

1.0.0

### Deployment Method

Amplify CLI

**Comment by fjnoyp** [comment]
Hi @jamilsaadeh97 thanks for posting this issue.  

Yes unfortunately this is expected behavior.  Even though event count is quickly updated, the filter and see the custom event takes ~30 minutes. 

We can update our documentation to be more clear about this behavior.  

If you want to see the events faster, instead of refreshing the AWS Pinpoint console, you can log out of the AWS console and log back in.
