### ISSUE TITLE
Read backed up EncryptedSharedPreferences

### ISSUE THREAD

**Issue by Smibser** [aws-amplify/amplify-flutter#2931]
### Description

The warning mentioned in [android documentation for EncryptedSharedPreferences](https://developer.android.com/reference/androidx/security/crypto/EncryptedSharedPreferences) says that you should exclude all `EncryptedSharedPreference`s from the auto backup. Since this is a library, it's not possible to control the backup rules. 
I found that there was added a workaround to the android package https://github.com/aws-amplify/amplify-android/pull/2113
But in the Flutter package, I can't find this workaround https://github.com/aws-amplify/amplify-flutter/blob/main/packages/secure_storage/amplify_secure_storage/android/src/main/kotlin/com/amazonaws/amplify/amplify_secure_storage/amplify_secure_storage/EncryptedKeyValueRepository.kt

Am I missing something or is this workaround missing in the flutter package?

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Storage

### Platforms

- [ ] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.7.12

### Amplify Flutter Version

1.0.0

### Deployment Method

Custom Pipeline

**Comment by Jordan-Nelson** [comment]
Hello @Smibser - A similar solution was implemented in in Amplify Flutter in https://github.com/aws-amplify/amplify-flutter/pull/2637. 

As noted in the docs, the issue with backing up the file is that it will be unreadable when it is restored since the encryption keys are never backed up.
> When restoring the file it is likely the key used to encrypt it will no longer be present

The implementations in Amplify Flutter and Amplify Android are a bit different, but they achieve the same thing. Both of them prevent a backed up file from being read. In Amplify Flutter, the preferences file will be deleted (if it exists) on the first app launch after a new install before any read/writes are made.

You should be able to add the file to the no backup rules as well if desired. The full path of the file used within auth will be `/data/data/<your_app_id>/shared_prefs/com.amplify.awsCognitoAuthPlugin.xml`. You can see this in Android Studio in the Device File Explorer. 

![Screen Shot 2023-04-25 at 9 47 19 AM](https://user-images.githubusercontent.com/20613561/234297587-5c9f5874-3709-4942-a65f-4fd862ac5c5e.png)

Encrypted data for analytics and push notification use separate files. The file names follow the pattern `com.amplify.<scope_name>.xml`. You can see the AmplifySecureStorageScope values [here](https://pub.dev/documentation/amplify_secure_storage_dart/latest/amplify_secure_storage_dart/AmplifySecureStorageScope.html).

**Comment by Smibser** [comment]
Thank you for this detailed answer. This answers all my questions
