### ISSUE TITLE
Question - DynamoDB vs AppSync in Lambda

### ISSUE THREAD

**Issue by jamilsaadeh97** [aws-amplify/amplify-flutter#3068]
Hi everyone, I just have a question about a best practice and/or use cases.

I have a flutter application with Amplify. I deployed some lambda functions using the CLI to update some items in my tables.
In the docs I saw that there are two ways to do so: Either using DynamoDB or AppSync GraphQL Api.
Is there any guidelines or specific use cases on when to use each? 
For example to update an item in my table when a change in my DynamoDB stream occur, should I update it using DynamoDB or AppSync?

Thank you!

**Comment by ragingsquirrel3** [comment]
Hey @jamilsaadeh97 good question! There isn't a very specific recommendation/answer to your question, but I will try to provide some context that may guide your decision.

Your are correct in noticing that there are basically 2 choices w Amplify for managing a database, GraphQL API w AppSync or "other," which tends to be REST API, connected to a lambda which could do a variety of things, one of the most common being mutating dynamo DB (DDB) directly.

For GraphQL, note that you would still be using dynamo DB by default because AppSync is more of a middle layer GraphQL interface for some persistence layer, Dynamo DB being the default version provided by Amplify backends. Generally, I would say that the GraphQL API and accompanying schema configurations have more documentation/support in Amplify. You will find more examples for various use cases, especially regarding authentication and data modeling. There is also better support for a Flutter client application because there is model codegen for the GQL schema, so you can generate Dart models that will work with your GraphQL backend. In a Flutter application with static typing, this makes it much easier to integrate with your frontend application so you can use the types in your widgets and stuff like that. I would personally recommend starting with GraphQL unless you are aware of some specific use case that Amplify GraphQL would not support.

On the other hand, if you choose not to use GraphQL, you are much more on your own and outside the Amplify-specific recommendations, which might be good or bad depending on your use case and desired development experience. If you integrate your lambda with REST API, Amplify provides a way to authenticate those requests and the CLI can help integrate permissions for DDB tables in your lambda. After that, you are mostly on your own and free to integrate however you wish. Your DDB business logic will live in the lambda and you will be writing JS/Python code with the AWS SDKs to interact with dynamo DB directly. Again, could be good or bad depending on use case/DX you want.

Let me know if you have other questions that I can answer to help guide your decision here.

**Comment by abdallahshaban557** [comment]
Additionally @jamilsaadeh97 , if you are using CRUD operations and not really relying on real-time updates, then communicating directly with DDB should not be an issue. However, if you are using Real-time subscriptions or utilizing DataStore, then we highly recommend that you make your changes through GraphQL API from AppSync.

Please let us know if you have more questions!

**Comment by jamilsaadeh97** [comment]
Hi @ragingsquirrel3 and @abdallahshaban557  , first of all thank you so much for this detailed explanation.

Based on both responses, I think it's best to use GraphQL API in my case since I rely heavily on real time updates.

But now I have another question related to AppSync. In my amplify configuration, the authorization providers are Cognito User Pools and IAM (I didn't add API key). In that case, should every request to AppSync in my Lambda be signed with: 
```  js
const signer = new SignatureV4({
    credentials: defaultProvider(),
    region: AWS_REGION,
    service: "appsync",
    sha256: Sha256,
  });
```
Or can I send requests without the signer? 

Thank you a lot!

**Comment by ragingsquirrel3** [comment]
Yes, I believe if calling from a lambda with IAM mode you will still have to sign and there is more info on https://docs.amplify.aws/guides/functions/graphql-from-lambda/q/platform/flutter/#iam-authorization, not sure about User Pools (there is example there too for api key and how the CLI can help authorize that way even though I know you said you didn't use that mode). If calling from the Flutter application directly (not a Lambda), of course you will not need to sign as the Amplify API category will sign it.

**Comment by jamilsaadeh97** [comment]
Thank you so much!
