### ISSUE TITLE
On migration from SDK 0.6.12 to 1.0.0 the app with a signed in user throws SignedOutException

### ISSUE THREAD

**Issue by matthewfx** [aws-amplify/amplify-flutter#3121]
### Description

I've decided to finally upgrade to 1.0.0. My previous version was 0.6.12

The problem is that if I have a user signed in to the app after the upgrade when I call

`final session = await Amplify.Auth.getPlugin(
      AmplifyAuthCognito.pluginKey,
    ).fetchAuthSession();`

I'm getting `SignedOutException`.

It means the user needs to sign in again and that is not the greatest UX.
Is there a way to prevent it?

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [X] Authenticator
- [ ] DataStore
- [ ] Storage

### Platforms

- [X] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.7.9

### Amplify Flutter Version

1.0.0

### Deployment Method

Amplify CLI

**Comment by Jordan-Nelson** [comment]
Okay, please let us know if you see it in the future. Credentials are stored in a new location in the iOS keychain in v1 but they should be automatically migrated on the first app launch after upgrade. 

If the app is uninstalled and then reinstalled the user will be signed out. That is intentional.
