### ISSUE TITLE
Missing nonce when using AWS Cognito HostedUI

### ISSUE THREAD

**Issue by PritamDutt** [aws-amplify/amplify-flutter#3129]
### Description

As per the current release of the sdk, it is [mandatory](https://github.com/aws-amplify/amplify-flutter/blob/6cfeb6888a9070279d7fbeea6dc5addbfc0bda49/packages/auth/amplify_auth_cognito_dart/lib/src/model/session/cognito_user_pool_tokens.dart#L79) for presence of `nonce` in idToken (JWT) for authentication to go through, which is not possible if one has implemented AWS Cognito Hosted UI as per the following links:

- [the usage of AWS SDK and AdminIntiateAuth/InitiateAuth does not allow the providing of a nonce as the per the issuance of the JWTs.](https://repost.aws/questions/QUAAEx8DD7R-62BUgMreYb2w/cognito-idp-include-nonce-token-in-id-token)

- [You can't modify the `nonce` claim ](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-pre-token-generation.html)

My suggestion would be to relax this requirement, by the means of may be some configurable flag till we have blessings of Cognito Team 🤓

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Storage

### Steps to Reproduce

1. Setup a Cognito user pool with custom hosted e.g. [AWS Sample](https://github.com/awslabs/aws-amplify-identity-broker/)
2. Create a user the pool
3. Create a client id
4. Setup flutter app
5. Configure Flutter App to use the client id setup in Step 3. above [AWS Sample](https://github.com/aws-amplify/amplify-flutter/tree/main/packages/auth/amplify_auth_cognito/example)
6. Choose to login using hosted ui 

Result: you get missing nonce error

### Platforms

- [ ] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.3.10

### Amplify Flutter Version

1.1.0

### Deployment Method

Amplify CLI

**Comment by dnys1** [comment]
Hi @PritamDutt, sorry you are facing this issue. This seems to be an issue in the identity broker implementation (https://github.com/awslabs/aws-amplify-identity-broker/issues/127) since both the [OpenID Connect specification](https://openid.net/specs/openid-connect-core-1_0.html#IDTokenValidation) and Cognito's own [docs](https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-using-the-id-token.html) mandate the inclusion of a `nonce` value in the ID token when it's sent with the authorization request.

If we changed the implementation to accommodate the identity broker, we would potentially be lowering the security posture for Cognito users. I'm not sure how best to handle the situation, but I will bring it to the attention of my team to see what we can do.

**Comment by dnys1** [comment]
Hi @PritamDutt, we are looking into removing the nonce check since it seems to mainly protect against replay attacks with the implict OAuth grant, which we don't support. I will keep you posted on the progress and have opened a PR [here](https://github.com/aws-amplify/amplify-flutter/pull/3321) if you want to work with that in the meantime.

**Comment by dnys1** [comment]
Hi @PritamDutt, sorry for the long delay on this. The fix has been merged and will be released in the near future.

**Comment by dnys1** [comment]
@PritamDutt this has been fixed in Amplify Auth v1.3.1. Thanks for your patience resolving this issue.
