### ISSUE TITLE
[IncomingAsyncSubscriptionEventToAnyModelMapper] The operation couldn’t be completed. (AWSPluginsCore.AnyModel)

### ISSUE THREAD

**Issue by krosiek** [aws-amplify/amplify-flutter#3231]
### Description

I have subscription. When I perform mutation, the mutation seems to be performed without any error and new entry can be explored in DynamoDb. But in Debug Console  I get the following error:
```
[IncomingAsyncSubscriptionEventToAnyModelMapper] The operation couldn’t be completed.
(Amplify.GraphQLResponseError<AWSPluginsCore.MutationSync<AWSPluginsCore.AnyModel>> error 0.)
```
and the subscription is not updated with new element.

For the purpose of bug report I simplified model to contain only ID and INT as still it gives the same error. 
I didn't modify mutations and subscriptions generated by Amplify.

Subscriptions related to other models work without any problems.
As a developer I definitely need more info about the error to be able fix it.
I will appreciate any help and a hint whether it's something on our side or a bug.

amplify versions:
```
  amplify_api: ^1.1.1
  amplify_auth_cognito: ^1.1.1
  amplify_datastore: ^1.1.0-supports-only-mobile+1
  amplify_flutter: ^1.1.1
```
Amplify CLI version
```
12.1.0
```

### Categories

- [ ] Analytics
- [ ] API (REST)
- [X] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [X] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Steps to Reproduce

1. Start subscription
2. Perform mutation 

### Platforms

- [X] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.10.5

### Amplify Flutter Version

1.1.1

### Deployment Method

Amplify CLI

### Schema

```GraphQL
/* Copied only lines related to UsageEntryDb subscription and mutation */
type UsageEntryDb @model @auth(rules: [{allow: owner, operations: [create, read, update]}]){
  id: ID!
  number: Int!
}

input CreateUsageEntryDbInput {
	id: ID
	number: Int!
	_version: Int
}

input ModelSubscriptionUsageEntryDbFilterInput {
	id: ModelSubscriptionIDInput
	number: ModelSubscriptionIntInput
	and: [ModelSubscriptionUsageEntryDbFilterInput]
	or: [ModelSubscriptionUsageEntryDbFilterInput]
	_deleted: ModelBooleanInput
}

input ModelUsageEntryDbConditionInput {
	number: ModelIntInput
	and: [ModelUsageEntryDbConditionInput]
	or: [ModelUsageEntryDbConditionInput]
	not: ModelUsageEntryDbConditionInput
	_deleted: ModelBooleanInput
}

type ModelUsageEntryDbConnection @aws_iam
@aws_cognito_user_pools {
	items: [UsageEntryDb]!
	nextToken: String
	startedAt: AWSTimestamp
}

input ModelUsageEntryDbFilterInput {
	id: ModelIDInput
	number: ModelIntInput
	and: [ModelUsageEntryDbFilterInput]
	or: [ModelUsageEntryDbFilterInput]
	not: ModelUsageEntryDbFilterInput
	_deleted: ModelBooleanInput
}

input UpdateUsageEntryDbInput {
	id: ID!
	number: Int
	_version: Int
}

type UsageEntryDb @aws_iam
@aws_cognito_user_pools {
	id: ID!
	number: Int!
	createdAt: AWSDateTime!
	updatedAt: AWSDateTime!
	_version: Int!
	_deleted: Boolean
	_lastChangedAt: AWSTimestamp!
	owner: String
}

type Mutation {
//...
@aws_cognito_user_pools
	createUsageEntryDb(input: CreateUsageEntryDbInput!, condition: ModelUsageEntryDbConditionInput): UsageEntryDb
//...

type Subscription {
/*...*/
@aws_iam
@aws_cognito_user_pools
	onCreateUsageEntryDb(filter: ModelSubscriptionUsageEntryDbFilterInput, owner: String): UsageEntryDb
		@aws_subscribe(mutations: ["createUsageEntryDb"])
/*...*/
```

**Comment by HuiSF** [comment]
Where did you perform the mutation from @krosiek in AppSync console?
When you explore the update record in your DDB, does it have values on `_deleted`, `_lastChangedAt` and `_version`?

**Comment by krosiek** [comment]
Hi @HuiSF, thank you for your questions.
I performed mutation from code:
```
final request = ModelMutations.create(usageEntry);
final response = await Amplify.API.mutate(request: request).response;
```
in DDB it does have `_lastChangedAt` and `_version` but there is no `_deleted` field.

**Comment by ragingsquirrel3** [comment]
@krosiek thanks for the info. Another question: How is the subscription made? Is it one of the automatic subscriptions from datastore or was it made with API category `Amplify.API.graphql...`? If so, could you include the code for the subscription?

If the model has _lastChangedAt, _version or _deleted, one possible error that might be happening is that subscription selection sets need to be a subset of the mutation selection sets. If you are making the mutation with mutation helper `ModelMutations.create` then the selection set will not include conflict resolution fields like _lastChangedAt, etc... So I would expect a subscription from datastore to have an error like this (bc the datastore subscriptions will include these fields and thus will not be a subset of the mutation selection set). One thing you could try is making the mutation request with a manual GraphQL document string that includes all the fields (including _lastChangedAt, _version, etc...) so that any subscription will be a subset of that selection set. There are some examples of this on https://docs.amplify.aws/lib/graphqlapi/advanced-workflows/q/platform/flutter/#subset-of-data although that is for a different use case (subset instead of complete set) it should point you in the right direction if this is the root cause of the issue you are having.

**Comment by krosiek** [comment]
Hi @ragingsquirrel3, the subscription is made from DataStore `observeQuery`
```
final Stream<QuerySnapshot<UsageEntryDb>> stream =
          Amplify.DataStore.observeQuery(UsageEntryDb.classType);
```
I will try to write mutation based on the subset example you provided and get back to you.

**Comment by krosiek** [comment]
@ragingsquirrel3 Thank you for pointing me out in the right direction. 
I was sure I used `DataStore` mutation instead of `API.mutate`.🙈

For anyone coming to the issue:
If you use `DataStore.observeQuery` make sure you use `DataStore.save` to insert items or if you use `API.mutate` make sure all fields defined in the model are included in the mutation (e.g. `_deleted`, `_lastChangedAt`, `_version`).
Many thanks!
