### ISSUE TITLE
Question - Datastore clarification

### ISSUE THREAD

**Issue by jamilsaadeh97** [aws-amplify/amplify-flutter#3405]
Hi everyone!

I have a question regarding Amplify Datastore and how it works internally.
Does it "download" all data to the device as a base query? 
Let's say for example I have a delivery application and a table called Order. When a user installs the application, does Datastore download all "Orders" items from the cloud to the device? 
If that's the case then the user device will have orders that do not belong to that user right?

I also saw in the documentation somewhere that the base query "hydrates" Datastore by default with 100 items or 1000. Nevertheless, is this considered bad since the device might be populated with items that the user will never use or see?

Thank you for any clarifications!

**Comment by ragingsquirrel3** [comment]
Good question. Yes, it is correct that DataStore with cloud sync by default syncs the entire database, but there are a few tools available to control/limit this based on use case:
* `syncExpressions` as documented on https://docs.amplify.aws/lib/datastore/sync/q/platform/flutter/#selectively-syncing-a-subset-of-your-data. This will let you state which subset of some model should go to this device, so for your use case, you could write a filter for orders that belong to the user.
* * owner auth in your GraphQL schema. As documented on https://docs.amplify.aws/lib/datastore/sync/q/platform/flutter/#selectively-syncing-a-subset-of-your-data, this makes it so when a user queries against a table they will only get the items which belong to them. Because AppSync controls this access, you wouldn't have to implement same logic in `syncExpression` because any query to AppSync will only return the entries for which signed in user has access.

**Comment by jamilsaadeh97** [comment]
Hi @ragingsquirrel3 thanks a lot for the clarification!

I was looking into it and decided that maybe it's best to move to Amplify API GraphQL instead of DataStore. 
However I'm lost trying to mimic the same functionality of Amplify.DataStore.observeQuery() with Amplify API.
I feel that it will need a lot of boilerplate code to have the same result as a simple observeQuery since my applications rely heavily on realtime data.

Could you guide me if there's a good way to do so with API or maybe if I'm missing something.

Thanks a lot!

**Comment by ragingsquirrel3** [comment]
Good question! There is [an open feature request](https://github.com/aws-amplify/amplify-flutter/issues/2414) for `observeQuery()` in API category and no easy way to replicate this in API at the moment. As mentioned in that issue, one option is to create multiple subscriptions for `onCreate`, `onUpdate`, `onDelete` etc... and combining the resulting streams. Subscriptions take a server-side `where` clause. This is complicated but easiest way to do it now if you require websocket updates. Another option without websockets would be to simply poll the query repeatedly which obviously might be expensive depending on use case, noting that some third-party libraries implement their `observeQuery()` this way.

**Comment by jamilsaadeh97** [comment]
This feature would be really great in my opinion. Hope that it will be available soon.

Thank you so much for your help @ragingsquirrel3 !
