### ISSUE TITLE
Login throws UserNot Confirmed even password is wrong

### ISSUE THREAD

**Issue by codesculpture** [aws-amplify/amplify-flutter#3407]
### Description

I have mandatory that every user needs to verified through their Email Address.
When anyone logs in, i need to detect if they are not verified and need to show the verification page (where they can type verification code), I am doing this by just Amplify.auth.login and catching UserNotConfirmed Exception. But the problem is it is throwing UserNotConfirmedException even the password is wrong, isnt the NotAuthorizedException needs to be thrown ?

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Platforms

- [ ] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.7.12

### Amplify Flutter Version

0.6.10

### Deployment Method

Amplify CLI

**Comment by Jordan-Nelson** [comment]
Hello @codesculpture - When the user is not confirmed, Cognito will return a UserNotConfirmedException regardless of the password being correct. The behavior you are seeing is the expected behavior in Amplify 0.6.10. 

We have modified this behavior a bit in the latest version, although it is similar. Starting in v1.0, instead of throwing a `UserNotConfirmedException`, signIn() will return successfully with a next step of `AuthSignInStep.confirmSignIn`. As you can see in [the docs for 1.0](https://docs.amplify.aws/lib/auth/signin/q/platform/flutter/#sign-in-a-user), we recommend re-sending the confirmation code in this case (and directing the user to the confirm account screen).

Once the user has received the code and confirmed their account, you could either redirect them back to the sign in flow, or attempt to automatically sign them in (if you keep the password they entered in memory). If you do attempt to automatically sign them in, you will have to handle the case in which the password is not correct. I would recommend returning the user to the sign in screen and presenting them with some sort of message to let them know that their account is confirmed but the password they had entered was incorrect.

I think the behavior here makes sense as the next step for the user will be to confirm their account regardless of whether or not the password is correct, and confirming the account doesn't require the password. Is there a use case you are not able to achieve with the behavior as it is?

**Comment by codesculpture** [comment]
This is what am currently doing, but u know am just try to prevent user not to show verification page even the password is wrong. I just need to know first password is incorrect or not when they try to log in.

**Comment by Jordan-Nelson** [comment]
@codesculpture - You could enable the flag `PREVENT_USER_EXISTENCE_ERRORS` in your userpool, which would have the desired effect in this specific use case. Auth.signIn() would then throw a NotAuthorizedException in both cases (incorrect password or user not confirmed). Auth.signIn() would only return the user not confirmed result once the password was correct.

This flag is intended to prevent errors from revealing the existence of a user. Enabling this would impact the errors returned from Auth.signIn() and well as other APIs. See [the Cognito docs](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pool-managing-errors.html?icmpid=docs_cognito_console_help_panel) and [this post](https://repost.aws/knowledge-center/cognito-prevent-user-existence-errors) for more info on the result of enabling that flag.

**Comment by Jordan-Nelson** [comment]
@codesculpture - I am going to close this out since we have not heard back.

As I mentioned above, the behavior you are seeing is expected. You could change the behavior with the PREVENT_USER_EXISTENCE_ERRORS option, but please be aware of all of the impacts of that flag.

If you believe you have a use case that isn't solved by these options, please share some details of the use case. Thanks.

**Comment by codesculpture** [comment]
I have use case, say here if u need to send verification email to unverified user (while login not signup) so here i need to send email to that user, so by the approach i done above (if userNotConfirmed been thrown, storing pass and verifying and again trying log in using the saved pass. But it leads to anyone can request verification code for any email. As u said i can do that PREVENT_EXISTENCE_USER flag, but i wish this to be something by default enabled (i.e throwing UserNotConfirmed even when the pass is wrong) anyway u can consider this as a suggestion, so i leave it as closed
