### ISSUE TITLE
DataStore contains() predicate doesn't work on a list of defined model type

### ISSUE THREAD

**Issue by afnx** [aws-amplify/amplify-flutter#3433]
### Description

When attempting to apply the `contains()` predicate on a query to filter data that has a list field with defined model type values, I encounter an error saying that there is no such column.

Here is the complete console output:

```console
no such column: root.friends in "select
  "root"."id" as "id", "root"."createdAt" as "createdAt",
  "root"."email" as "email", "root"."name" as "name",
  "root"."updatedAt" as "updatedAt"
from "User" as "root"
where 1 = 1
  and instr("root"."friends", ?) > 0
order by "root"."name" asc
limit 20 offset 0"
Query API failed. Error = DataStoreError: The operation couldn’t be completed. (SQLite.Result error 0.)
Recovery suggestion: The operation couldn’t be completed. (SQLite.Result error 0.)
Caused by:
no such column: root.friends (code: 1)
```

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [X] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Steps to Reproduce

1. Create a project with the schema below.
2. Use the following code to query the data:
```dart
Future<List<User>?> getUserFriends(String userId) async {
    try {
      return await Amplify.DataStore.query(
        User.classType,
        where: User.FRIENDS.contains(userId),
      );
    } on Exception catch (error) {
      debugPrint(error.toString());
      return null;
    }
  }
}
```
3. Run the app on Xcode.
4. Check the console for the detailed error.

### Platforms

- [X] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.10.5

### Amplify Flutter Version

1.2.1

### Deployment Method

Amplify CLI

### Schema

```GraphQL
type User @model {
  id: ID! @index(name: "byUser")
  name: String!
  email: String!
  friends: [User!] @hasMany(indexName: "byUser", fields: ["id"])
}
```

**Comment by Equartey** [comment]
Hey @afnx 

`.contains()` currently does not support a list of models. Rather it should work on values stored as `Strings`.

**Comment by afnx** [comment]
@Equartey, thank you for your reply. What are some workarounds you could suggest until this feature is implemented? 

I don't want to create separate models for the user friendship logic because I sometimes need to query user friends with additional predicates like this:

```dart
final userFriendsWithName = await Amplify.DataStore.query(
  User.classType,
  where: User.FRIENDS.contains(userId).and(User.NAME.beginsWith(searchValue)),
);
```

**Comment by Equartey** [comment]
@afnx unfortunately I don't have any server side filtering workarounds. 

Acknowledging the performance hit this could take on larger data sets. I would consider filtering the friends' list on the client side to get something working.

Additionally, I found existing feature requests for this issue: https://github.com/aws-amplify/amplify-flutter/issues/1502 & https://github.com/aws-amplify/amplify-flutter/issues/1449

Since this is a duplicate, I'm going to close this issue to centralize the discussion to the above issues.

**Comment by afnx** [comment]
@Equartey, I see. Client side filtering is not really an option for me.

What are the consequences of creating an extra field to store the IDs of user friends?

```graphql
type User @model {
  id: ID! @index(name: "byUser")
  name: String!
  email: String!
  friends: [User!] @hasMany(indexName: "byUser", fields: ["id"])
  friendIds: [ID!]
}
```

If an user has thousands of friends, so need to store thousands of IDs, would it cause any performance issues every time I query the User model?

**Comment by Equartey** [comment]
Hey @afnx,

That seems like a good way to solve your problem. I'm assuming you already realized this, but given that updated schema you can craft a query similar to what you originally had. This is because the `ID` field gets passed as a `String`. 

```dart
final userRes = await Amplify.DataStore.query(
  User.classType,
  where: User.NAME.beginsWith(searchValue).and(User.FRIENDIDS.contains(userId)),
);
```

As for performance concerns, there is probably a negative impact during network sync due to duplicate data [(denormalization)](https://aws.amazon.com/blogs/database/should-your-dynamodb-table-be-normalized-or-denormalized/) 

If performance becomes problematic, perhaps reconsider the structure of your model to represent the relationship by using multiple models and indexes.
