### ISSUE TITLE
Data not retrieved on Initial Request

### ISSUE THREAD

**Issue by codesculpture** [aws-amplify/amplify-flutter#3481]
when user open the app first time (there is no data locally cached)

I started sync when user opened using

Amplify.DataStore.start()

And on the first query, Amplify.DataStore.query()
I cant get the data, instead i can get the data when i queried next time.

So here we need to get data initially at the first query right. Seems internally it was got data and stored it locally when the first query made but not returned the result. So if i make the second query it will instantly returning the result.

Am doing two query, fake query first and making another query again to get the result..🥲

**Comment by Jordan-Nelson** [comment]
Hi @codesculpture - `DataStore.query()` always operates against the data that is already on the device. When the app first starts up there will not be any data on the device, which is why the first query comes back empty.

Once you call `DataStore.start()`, an initial sync begins (note: most DS operations call start for you if you do not call it yourself). By default, the initial sync includes all the records that the user is authorized to access from your cloud data source (see how to customize that [here](https://docs.amplify.aws/lib/datastore/sync/q/platform/flutter/#selectively-syncing-a-subset-of-your-data)).

You can call `DataStore.query()` during the initial sync, but this will continue to only operate against the local device. It will not wait for the sync process to complete. So if you call query during the initial sync you will likely get either no records, or an incomplete set. There are a few options that you can use to get data immediately after the sync completes.

1. Use `DataStore.observeQuery()` ([docs](https://docs.amplify.aws/lib/datastore/real-time/q/platform/flutter/#observe-query-results-in-real-time)) 

observeQuery returns a stream of snapshots during initial sync. Each snapshots represents the data synced to your device at that moment. The events emitted contain an indicator to determine if the data is fully synced. You can use this to ignore the events until a full sync completes.

```dart
void observeQuery() {
  final snapshot = await Amplify.DataStore.observeQuery(Post.classType).firstWhere((snapshot) => snapshot.isSynced);
  print(snapshot.items);
}
```

2. Wait for the `ready` event.

DataStore will emit a `ready` event when the full DB has finished syncing. You can wait for this event before performing any queries. See [docs](https://docs.amplify.aws/lib/datastore/datastore-events/q/platform/flutter/#ready) for more info.

**Comment by codesculpture** [comment]
I understood, but wouldnt that be seem weird. Same function is behaving differently at different time. Closing this now but please consider to make it better like add waiting behavior to query method if its a initial request
