### ISSUE TITLE
Amplify ModelQueries.list() returns null

### ISSUE THREAD

**Issue by SK-SAYED-AKTAR** [aws-amplify/amplify-flutter#3537]
### Description

My flutter version: Flutter 3.10.6 • channel stable
Package version listed below:
amplify_core: 0.6.12
amplify_flutter: 0.6.12
amplify_storage_s3: 0.6.12
amplify_api: 0.6.12

**The Problem**
```
final request = ModelQueries.list(Request.classType, limit: 50,  where: Request.ACTIVE.eq(true));
final response = await Amplify.API.query(request: request).response;
print(response.data) it's basically returns _null_.
```

Previously It worked but currently I'm facing this error. Whenever I try to get the List of items from dynamodb using amplify api, it returns _null_.

Apart from this I'm also facing the same problem for authentication.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [X] API (GraphQL)
- [X] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Platforms

- [ ] iOS
- [X] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.10.6

### Amplify Flutter Version

0.6.12

### Deployment Method

Amplify CLI

**Comment by ragingsquirrel3** [comment]
Sorry you are facing this issue. A few followup questions to give us more info here:
* When the `response.data` is `null`, can you print/debug `response.errors`? In most cases, when the response data is null it is because of server-side errors which come back in `response.errors` (often validation/auth, etc... errors).
* Are you able to make this request in the AppSync console? If so, what response do you get with data/errors? This is helpful to isolate any error that might be from the client library vs. the backend.

**Comment by SK-SAYED-AKTAR** [comment]
Thank you for your quick response. We realised that the API Key was expired but there was no sign or notification on the console to help us understand the underline issue. So the issue has been resolved.
