### ISSUE TITLE
Datastore is doing a full sync of unnecessary Data

### ISSUE THREAD

**Issue by vishalkhialani** [aws-amplify/amplify-flutter#3552]
### Description

Please review the schema section. Please note `Post` belongs to `User`. 

We have around 1 million Users and we have around 2 million Posts.
For performance reasons, we do not want datastore to sync 10k ( default value ) records.
We have written the below code to reduce the count.

`syncExpressions: [
DataStoreSyncExpression(
Post.classType,
            () {
                return Post.CREATEDAT.gt(TemporalDateTime(DateTime(2023, 8, 8)));
            } ,
          ),
        ],
`

However as `Post` belongs to `User` datastore syncs all the records from the `User` model. This is a performance issue for us. We want to only pull the `User` records for the `Posts` that were created after `2023,8,8`

![Screenshot by Dropbox Capture](https://github.com/aws-amplify/amplify-flutter/assets/50231479/f32f6888-e111-4a37-9453-d81dfd8518ea)

Also as per the [selective sync documentation](https://docs.amplify.aws/lib/datastore/sync/q/platform/js/#selectively-syncing-a-subset-of-your-data) we can revaluate using Datastore.stop() and then Datastore.start(). However this also does not work for us. Is this a known bug. We did not find this as an open issue.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [X] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Steps to Reproduce

1. Create two Models.
2. Build a relationship between them of @belongsTo
3. Then do a sync where the main model has a selective sync enabled.
4. The other model does not adhere to this filter.

### Platforms

- [X] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.10.6

### Amplify Flutter Version

1.3.1

### Deployment Method

Amplify CLI

### Schema

```GraphQL
type Post @model @auth(rules: [{allow: owner, operations: [create, update]}, {allow: public, operations: [create, update, read]}, {allow: private, operations: [read]}, {allow: private, provider: iam, operations: [read, update]}]) {
  id: ID!
  body: String
  userID: ID! @index(name: "byUser")
  author: User @belongsTo(fields: ["userID"])
  createdAt: AWSDateTime
}

type User @model @auth(rules: [{allow: owner, operations: [create, update]}, {allow: public, operations: [create, update, read]}, {allow: private, operations: [read]}, {allow: private, provider: iam, operations: [read]}]) {
  id: ID!
  userAddress: String
  posts: [Post] @hasMany(indexName: "byUser", fields: ["id"])
  createdAt: AWSDateTime
}
```

**Comment by Souf-O** [comment]
Thank you for providing your schema. Given your data model, here's how you can approach limiting the synchronization of User records based on the creation date of associated Posts:

1. Add a Sync Expression for Users:
   - Since you want to limit User records based on the Posts created after a certain date, you can define a sync expression for the User model.
   - The sync expression should filter Users based on the associated Posts' creation dates. You'll need to define this logic in the sync expression function.
   - Here's a general idea of what the sync expression could look like:


syncExpressions: [
  DataStoreSyncExpression(
    User.classType,
    () {
      return User.POSTS.createdAt.gt(TemporalDateTime(DateTime(2023, 8, 8)));
    },
  ),
],


2. Ensure Proper Associations:
   - ensure that User records are correctly associated with the Posts they've authored.
   - Your existing schema seems to have the appropriate association (`author: User @belongsTo(fields: ["userID"])`) in the Post model.
   - Double-check that the `userID` field in the Post model indeed references the `User` who created the post.

**Comment by amitvrm036** [comment]
Hi @Souf-O , thanks for your reply , I am co-working with @vishalkhialani on the same issue , I checked your following code
>
>syncExpressions: [
DataStoreSyncExpression(
User.classType,
() {
return User.POSTS.createdAt.gt(TemporalDateTime(DateTime(2023, 8, 8)));
},
),
],
>
but this expression is not a valid expression , `createdAt` or anything similar is not defined on User.POSTS object , I tried other combinations to query Users according to Posts condition , for example `User.POSTS.eq(Post.CREATEDAT.ge(TemporalDateTime(DateTime(2023, 8, 8))));`

but couldn't get success with any combination of QueryPredicate.

**Comment by Equartey** [comment]
@vishalkhialani @amitvrm036 

We do not support nested predicates as suggested above. We have an open feature request for that here https://github.com/aws-amplify/amplify-flutter/issues/1449.

**Comment by Jordan-Nelson** [comment]
@vishalkhialani - I am going to close this out since we have not heard back. I think the suggested sync expression would solve your use case if nested predicates were supported. As mentioned above, there is an existing issue tracking support for nested predicates. Please let us know if you are facing any other issues.

**Comment by vishalkhialani** [comment]
> 

the sync expression did not work. We decided to use SQLite instead of Datastore as it does not support nested predicates. You might want to write it in the readme file as many projects might deem this as a critical feature.
