### ISSUE TITLE
GraphQL WebSocket automated reconnection seems broken

### ISSUE THREAD

**Issue by ainomegumi-desu** [aws-amplify/amplify-flutter#3740]
### Description

I`m testing auto reconnection under WI-FI to 4G、4G to Another-4G, 4G to WI-FI etc. the automated reconnection seems not work
   

  
1 Losing NetworkLossEvent

change phone network 4G to WI-FI, quite often the underlying code won't trigger `NetworkLossEvent` event ( especially when the underlying code not executing ping-pong, so it won't trigger `PollFailedEvent`), but it will trigger `NetworkFoundEvent` event. i guess in this situation the reconnect logic won't get executed ?

2 No websocket mesage after reconnect

even though the reconnect logic get executed, i can ensure this by the underlying bloc logic get `SubscriptionStartAckEvent`. but the reconnected subscription won't get any new message from AppSync.

Am i missing somthing here ?  If so, sorry for the disturb

### Categories

- [ ] Analytics
- [ ] API (REST)
- [X] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Steps to Reproduce

1. subscribe to any appsync websocket API
2. change the phone network, so it will trigger reconnect logic
3. reconnect completed, but no new message get appeared

my amplify retry setting is 
`RetryOptions(maxAttempts: 5), pollInterval: Duration(seconds: 3))`

### Platforms

- [ ] iOS
- [ ] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.13.0

### Amplify Flutter Version

1.4.0

### Deployment Method

Amplify CLI

**Comment by Equartey** [comment]
Hey @ainomegumi-desu, sorry for the unexpected behavior.

I ran through some test cases both with and without your retry settings, both on iOS and Android. 

Here are some observations: 

- Without your retry settings -- app reconnects after network swaps (ie wifi/on/off/mobile/etc) and receives events emitted after reconnect.
- With you settings -- I saw depending on how long your device takes to swap connection the reconnection fails. This appears to be because of the limited number of retry attempts (we default to 8). Increasing this number improves the app's ability to successfully recover. 

Under the hood, we are using the [retry package](https://pub.dev/packages/retry) to determine when to test internet connection again. This package performs an exponential retry/back off, simply put, each subsequent attempt waits longer than the one before. The default setting of 8 attempts results in a ~50 second window of retrying. 

Here is a break down of those points in Milliseconds:
> 0. 0 ms --> first failure 
> 1. 400 ms +/- 25%
> 2. 800 ms +/- 25%
> 3. 1600 ms +/- 25%
> 4. 3200 ms +/- 25%
> 5. 6400 ms +/- 25%
> 6. 12800 ms +/- 25%
> 7. 25600 ms +/- 25%

Notice that only 5 attempts exponentially reduces the recovery window from 8 attempts. 

-----

> 2 No websocket mesage after reconnect

It may be easier to follow the subscription hub events as they are an aggregate of the underlying bloc's state. Try this following code snippet to view those logs while debugging.

```Dart
 Amplify.Hub.listen(
    HubChannel.Api,
    (ApiHubEvent event) {
      if (event is SubscriptionHubEvent) {
        print(event);
      }
    },
  );
```
Also note, any messages sent while the application does is not in the `SubscriptionHubEvent.status == 'connected` state, will not be received and need to be fetched when the connection is recovered manually. An example of this can be found on our [docs page](https://docs.amplify.aws/lib/graphqlapi/subscribe-data/q/platform/flutter/#automated-reconnection)

----

With all that in mind, can you try increasing your max attempts and see if the behavior persists? 

Please reach out if you have more questions.

**Comment by ainomegumi-desu** [comment]
@Equartey Thanks you for taking time to investigate

I still randomly ran into the issues, but it has nothing to do with the reconnection logic, i`ll dig futher to see the result and post below if it will help others

Sorry for the distrub
