### ISSUE TITLE
LambdaException instead UserNotFoundException

### ISSUE THREAD

**Issue by minusgat** [aws-amplify/amplify-flutter#3779]
### Description

In flutter amplify_auth_cognito package, when I provide a non-existing user, the resetPassword method throws LambdaException instead of UserNotFoundException, is this exception correct?

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [X] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Steps to Reproduce

with AuthCategory.resetPassword(username: 'jhon.doe@example.com') is call, a LambadaException instead UserNotFoundException is throw, this behavior is correct?

amplify_auth_cognito : ^1.4.2
flutter: 3.13.1
dart: 3.1.0

### Screenshots

![Captura de pantalla 2023-09-21 a la(s) 18 39 54](https://github.com/aws-amplify/amplify-flutter/assets/40323741/565704e2-fc9c-463d-a77d-d588dce8d547)

### Platforms

- [ ] iOS
- [x] Flutter 

### Flutter Version

3.13.1

### Amplify Flutter Version

3.1.0

### Deployment Method

Amplify CLI

**Comment by Jordan-Nelson** [comment]
Hi @minusgat - It looks like you have a [User Migration Trigger](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-migrate-user.html) setup for this User Pool. This trigger will be invoked when there is no user with the given username in the User Pool during Sign In or Forgot Password. Any exception returned from this lambda trigger will result in a LambdaException in Amplify Auth.

Let me know if you have any other questions.

**Comment by minusgat** [comment]
When I use 
AuthCategory.signIn(  username: email,  password: password);  => it throw UserNotFoundException
AuthCategory.resetPassword(  username: email);  => it throw LambdaException

Is it correct that there are different exceptions with these methods and the same email?

**Comment by Jordan-Nelson** [comment]
The User Migration Lambda is only invoked on sign in when using the `USER_PASSWORD_AUTH` auth flow. Amplify.Auth.signIn() uses SRP Auth by default. You can read more about User Password Auth and the user migration flow [here](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-import-using-lambda.html).

When using the `USER_PASSWORD_AUTH` flow, you should also see a LambdaException in this case. You will not see a LambdaException when using SRP since the Lambda is never invoked.

If you do want to use User Password auth during sign in, here is an example of how you can do that.

```dart
final result = await Amplify.Auth.signIn(
  username: _username,
  password: _password,
  options: const SignInOptions(
    pluginOptions: CognitoSignInPluginOptions(
      authFlowType: AuthenticationFlowType.userPasswordAuth,
    ),
  ),
);
```

Let me know if you have any other questions.

**Comment by minusgat** [comment]
A lot of thanks for the Cognito doc reference and your answers, 

The doubt was resolved!

**Comment by Jordan-Nelson** [comment]
@minusgat - I am glad that helped. I am going to close out since it sounds like this was resolved. Let me know if you face any other challenges.
