### ISSUE TITLE
Flutter amplify dataStore sync failure with more than 42 tables

### ISSUE THREAD

**Issue by AzharRaeisi** [aws-amplify/amplify-flutter#4296]
### Description

I am encountering a critical issue with Flutter Amplify DataStore sync when the number of tables exceeds 42. The sync process fails to operate entirely, and I am experiencing a complete breakdown in functionality. Datastore does not emit any sync event. There is just networkStatus event in hub as can be seen in the screenshot.

Amplify Datastore works fine if there are lower table numbers in dynamodb.

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [x] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Screenshots

![log](https://github.com/aws-amplify/amplify-flutter/assets/35802452/01d90135-00d6-4a0e-a907-989912bf9269)

### Platforms

- [x] iOS
- [x] Android
- [ ] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.13.9

### Amplify Flutter Version

  amplify_flutter: ^1.4.1   amplify_auth_cognito: ^1.4.1   amplify_api: ^1.4.0   amplify_datastore: ^1.4.1   amplify_storage_s3: ^1.4.0

### Deployment Method

Amplify CLI

**Comment by haverchuck** [comment]
@AzharRaeisi Thanks for reporting this issue. Which Flutter platforms are you testing on?

**Comment by AzharRaeisi** [comment]
@haverchuck Thanks for your response. Tested on IOS and Android

**Comment by haverchuck** [comment]
@AzharRaeisi I think this issue may be due to the fact that AppSync establishes a limit of 100 active subscriptions per client. It establishes 3 for each model, so we would typically expect this issue to occur if you have more than 33 models (although in this case you seem to have more - perhaps some of your tables are not backing models?). This is a soft limit and can be adjusted with a limit increase request to AppSync.

More information can be found [here](https://docs.aws.amazon.com/general/latest/gr/appsync.html#limits_appsync), including a link for increasing the limit.

**Comment by AzharRaeisi** [comment]
@haverchuck you are right I do have 33 models with more then 13 enums. I have increased the limit to 300, hope this will fix the problem. Thank you.

Another question will it cost more?

**Comment by haverchuck** [comment]
@AzharRaeisi I'd encourage you to check out the pricing information for [AWS AppSync](https://aws.amazon.com/appsync/pricing/). It is my understanding that in your situation you could potentially incur more charges because you would be receiving more "Real Time Updates", but this could also happen in other ways (such as increased activity by end users or an increase in end users). But I will defer to the pricing guide as the source of truth here.

**Comment by AzharRaeisi** [comment]
@haverchuck is it possible to avoid syncing a table entirely and only initiate sync if needed in the future? If not, does it mean that DataStore requires three subscriptions per DynamoDB table? Am I correct?

**Comment by haverchuck** [comment]
Yes, three subscriptions per model. We do have selective sync functionality to limit what actually gets transmitted across the wire, but the subscriptions are still establishe regardless, so this is not a solution currently.

We are tracking a feature request to improve this: https://github.com/aws-amplify/amplify-flutter/issues/1692

**Comment by AzharRaeisi** [comment]
@haverchuck, appreciate your generous support.
