### ISSUE TITLE
How to call Admin Queries API with authorization?

### ISSUE THREAD

**Issue by yvvivek9** [aws-amplify/amplify-flutter#4664]
I have enabled Admin Queries API and restricted it to user group known as Admin. I am using the following code,
```dart
try {
      const apiName = "AdminQueries";
      const path = "listUsersInGroup";
      // final session = await Amplify.Auth.getCurrentUser();
      // final headers = {
      //   'Content-Type': 'application/json',
      //   'Authorization': "${session.}",
      // };
      const queryParams = {"groupname": "Admin"};
      final operation = Amplify.API.get(path, apiName: apiName, queryParameters: queryParams);
      final response = await operation.response;
      safePrint("Response: $response");
 } on ApiException catch (e) {
      safePrint("Api Exception: $e");
      // showErrorSnackBar(content: e.message);
 } catch (e) {
      safePrint("Exception: $e");
      // showErrorSnackBar(content: "Error fetching data");
 }
``` 

This gives me an error saying "GET ..url.. failed: TypeError: Failed to fetch", url seems to be perfect including the api id. I have checked through docs however only js and swift code is available and am unable to figure this out. How do i get the auth session access token or is this a wrong approach. Kindly help, thank you.

**Comment by Equartey** [comment]
Hi @yvvivek9, sorry you're having troubling setting up the Admin API. 

I don't think there is an issue with the provided method. You do not need to explicitly define credentials on the request, its signed for you by the Amplify API call. 

More likely the permissions on the user are incorrect. Please ensure the user you are logged in as belongs to the group you setup via the CLI. This is captured in this section https://docs.amplify.aws/javascript/build-a-backend/auth/admin-actions/#enable-admin-queries. 

If you have added this permission, make sure you've signed out and signed back in to get a fresh token (my initial calls were failing due to this).

If your request is still failing, you can examine the Cloud Watch logs in the AWS console for the Lambda function and reference the lambda source code to further debug. The source code lives in your project under `amplify/backend/function/AdminQueriesXXX/src`, note changes to these files require an `amplify push` to update. To find the Lambda Cloud Watch logs simply search the Lambda console for your local folder name `AdminQueriesXXX` >  click the "Monitor" tab > click the chip "View CloudWatch logs" > locate the relevant log stream.

For reference, I was able to setup and verify a successful Admin API in Dart using the following code snippet: 

```dart
  Future<void> listAdmin() async {
    const path = "/listUsersInGroup";
    final query = {
      "groupname": "Admin",
    };
    const apiName = "AdminQueries";
    try {
      final restOperation = Amplify.API.get(
        path,
        queryParameters: query,
        apiName: apiName,
      );
      final response = await restOperation.response;
      print('GET call succeeded: ${response.decodeBody()}');
    } on ApiException catch (e) {
      print('GET call failed: $e');
    }
  }
```


If you are unable to resolve the error, please provide the full exception message and we are happy to help you further.

**Comment by Jordan-Nelson** [comment]
@yvvivek9 please let us know if you have any further questions.

**Comment by yvvivek9** [comment]
sorry i was off the grid, i got it working with ur solution tnx.
