### ISSUE TITLE
Refresh token using expired token - SessionExpiredException handling

### ISSUE THREAD

**Issue by gauravdangi** [aws-amplify/amplify-flutter#474]
**Describe the bug**
I am getting `SessionExpiredException` (Session expired could not fetch user sub) when a user's session is expired while fetching the user's Auth session 
`await Amplify.Auth.fetchAuthSession(options: CognitoSessionOptions(getAWSCredentials: true));`

Now I would like to refresh the token once it is expired without asking the user to re-login. So there should be a method using with we can use the previously expired token to sign-in the user back to the application. Otherwise, we'd have to store the user's username and password in the shared preference in order to auto-login and I'm not very sure if I should store the password in the shared preference.

How can we solve this problem? Is there any way I can get the new session so that users do not have to sign in manually?

**Expected behavior**
Should be able to auto-login once the session is expired

**Platform**
Amplify Flutter current supports iOS and Android.  This issue is reproducible in :
[.] Android
[.] iOS

**Comment by AndreyGuitar** [comment]
Guys, I'm really sorry, but this is not a feature-request.
This is a bug.
'Session-refresh' is a must-have functionality for all current auth services and cognito can't force me to store user credits :(
It will be a very challenging to pass the security check for the app storing credits in a raw format :(

**Comment by haverchuck** [comment]
@AndreyGuitar @gauravdangi Apologies- I misunderstood the issue when marking it as a feature request.  When this issue says 'refresh the token', do you mean the refresh token itself, or the access and id tokens? The latter should automatically refresh provided that the refresh token is still valid.

**Comment by Jordan-Nelson** [comment]
@gauravdangi or @AndreyGuitar would you mind providing some more info on the behavior you are experiencing versus the behavior you are expecting? If you can include reproduction instructions that would be great. It sounds like you may be experiencing a bug, and I would like to reproduce it so that we can look into a fix.

If the refresh token is still valid, the access and ID token should automatically refresh. If you are seeing different behavior, that sounds like a bug. Once the refresh token is expired, there is no way to refresh it without re-authenticating the user (for example, with username/password). Cognito allows the refresh token to be set to expire anywhere between 60 minutes and 3650 days, and the access/ID tokens can be set to expire anywhere between 5 minutes and 1 day.

**Comment by offlineprogrammer** [comment]
Hey @gauravdangi @AndreyGuitar 

I am closing this issue for now as we didn't hear from you
We can reopen it if you are still facing the issue and when you provide details

Regards
Mo
