### ISSUE TITLE
Using the modules independently

### ISSUE THREAD

**Issue by edwardaux** [aws-amplify/amplify-flutter#488]
I've got a question, rather than a bug - apologies if this isn't the right place for it.

I've got an existing app that uses an unofficial cognito library (amazon_cognito_identity_dart) but it appears to have been abandoned, so I'm looking at alternatives. Obviously, this project is the first one on my list.

I really only need the cognito module... do I have to install the whole amplify "ecosystem"? Or can each module be used in standalone mode?

I mean, I can see that for a lot of use cases having a complete package makes a lot of sense, but I'm a big fan of keeping my dependencies to the absolute minimum so would prefer to be able to use them independently if possible.

Thanks.

**Comment by Amplifiyer** [comment]
@edwardaux yes you can use some of the modules independently and amplify_auth_cognito is one of them. You still have to use the amplify_flutter top level package/facade to configure and setup everything, you won't need anything else.

If you were to use Storage or Analytics, then you also need to have amplify_auth_cognito since they depend on it for access credentials.

**Comment by edwardaux** [comment]
👍 thanks for the confirmation
