### ISSUE TITLE
Invalid argument: Instance of 'CognitoSignInOptions'

### ISSUE THREAD

**Issue by Deanwfy** [aws-amplify/amplify-flutter#512]
When I used 'CognitoSignInOptions', I got this expception:
```
#0   AuthenticationProvider.signIn
#1   <asynchronous suspension>
Invalid argument: Instance of 'CognitoSignInOptions'
```

Code:
```
Map<String, String> userAttributes = {
  'SECRET_HASH': 'xxxxxx'
};
var options = CognitoSignInOptions(clientMetadata: userAttributes);
var user = await Amplify.Auth.signIn(
    username: username, password: password, options: options);
```
How to fix it?
@Ashish-Nanda  @haverchuck

**Comment by brunovsiqueira** [comment]
@Deanwfy I am getting the same error and needing help asap.
https://github.com/aws-amplify/amplify-flutter/issues/506

**Comment by tcaravanabtg** [comment]
I'm trying to understand what is going on and I guess the error has something to do with the SignInRequest passing the Options as an instance of CognitoSignInOptions instead of a map.

The message_codec class that will consume it only deal with primitive types (boolean, integer, double, string, list, map), throwing the invalid argument exception.

**Comment by haverchuck** [comment]
@Deanwfy There is a [fix](https://github.com/aws-amplify/amplify-flutter/pull/519) for this in flight.

**Comment by Deanwfy** [comment]
Got it, thanks so much! @haverchuck @caravanat
