### ISSUE TITLE
Replace tuple with record types

### ISSUE THREAD

**Issue by flodaniel** [aws-amplify/amplify-flutter#5189]
### Description

Running `dart pub deps` in my project shows that smithy_aws still uses the tuple package. Any usage of tuple should be replaced by a Record type available starting in dart 3.
See https://pub.dev/packages/tuple which states: 
> We consider this package to be feature complete. With Dart 3.0, users now have the ability to use [Records](https://dart.dev/language/records):

Screenshot of dart pub deps:

<img width="292" alt="image" src="https://github.com/user-attachments/assets/4cdda57c-cf25-496c-9715-a1f078f7bb65">

### Categories

- [ ] Analytics
- [ ] API (REST)
- [ ] API (GraphQL)
- [ ] Auth
- [ ] Authenticator
- [ ] DataStore
- [ ] Notifications (Push)
- [ ] Storage

### Steps to Reproduce

Depend on `amplify_flutter`

### Platforms

- [X] iOS
- [X] Android
- [X] Web
- [ ] macOS
- [ ] Windows
- [ ] Linux

### Flutter Version

3.22.1

### Amplify Flutter Version

2.1.0

### Deployment Method

Amplify CLI

**Comment by Jordan-Nelson** [comment]
@flodaniel - Thanks for opening the issue. As the screenshot you have provided shows, tuple is being brought into your project via crclib, which is a dependency of smithy_aws. [crclib](https://pub.dev/packages/crclib) is maintained by Google. There is no version of crclib available yet that doesn't depend on tuple. If you have a need to remove all use of tuple from your project I would suggest opening an issue with crclib to ask for a new version that does not depend on tuple. `smithy_aws` has a loose version constraint on crclib: (version: ^3.0.0), so once there is a version of crclib that does not depend on tuple available you should be able to simply run `pub upgrade` to get the latest version and remove tuple from you project.

Let me know if you have any questions. Otherwise I will close this out since there isn't any action required in Amplify.

**Comment by flodaniel** [comment]
Thank you! I kinda missed/ignored that library in between.

**Comment by Jordan-Nelson** [comment]
No problem. I am going to close this issue.
