### ISSUE TITLE
Amplify Storage List returns empty list

### ISSUE THREAD

**Issue by smerchermek** [aws-amplify/amplify-flutter#559]
Amplify.Storage.list() returns empty list when used with existing buckets.
I have a problem while accessing the objects in my bucket, I can only access objects inside a folder named "Public".

**Comment by Jordan-Nelson** [comment]
Hi @smerchermek - Thanks for taking the time to open the issue. It sounds like you are looking for the ability to specify a custom prefix (instead of the public/protected/private prefixes). This is not currently supported. There have been a few separate issues for this. #416 is going to be used to track interest in this feature.

I'm going to mark this as a duplicate and close this issue out. Please provide any additional comments/questions on the other thread.
