### ISSUE TITLE
Null Safety Example

### ISSUE THREAD

**Issue by BesavedTech** [aws-amplify/amplify-flutter#564]
The example folder of the null safety master version, has not been migrated to null safety versions of the plugins.

**Comment by fjnoyp** [comment]
HI @BesavedTech thanks for pointing that out.  We are in the process of migrating to null safety but have not released anything publicly yet.  The example folder is not migrated yet because the plugins it relies on: Storage/Analytics have not been migrated to null safety.  We are working on that now: 

Analytics : https://github.com/aws-amplify/amplify-flutter/pull/483
Storage: https://github.com/aws-amplify/amplify-flutter/pull/485

**Comment by Ashish-Nanda** [comment]
**Amplify Flutter `0.2.0` with support for null safety is now released!**

The example apps have all been migrated to null safety as well. You can refer to this [branch](https://github.com/aws-amplify/amplify-flutter/tree/null-safety-master)

Please take a look at the docs for [instructions on how to migrate your app](https://docs.amplify.aws/lib/project-setup/null-safety/q/platform/flutter)

Do let us know if you have any questions or feedback.
