### ISSUE TITLE
[Feature Request] Equivalent of "setSignInUserSession" in flutter

### ISSUE THREAD

**Issue by fpabl0** [aws-amplify/amplify-flutter#845]
Hello, in [amplify-js](https://github.com/aws-amplify/amplify-js/blob/main/packages/amazon-cognito-identity-js/src/CognitoUser.js) there is a `setSignInUserSession` function, is there any equivalent of that function in Flutter?

**Comment by HuiSF** [comment]
Thanks for the explanation. Currently, both [amplify-ios ](https://github.com/aws-amplify/amplify-ios/tree/main/Amplify/Categories/Auth)and [amplify-android](https://github.com/aws-amplify/amplify-android/blob/main/aws-auth-cognito/src/main/java/com/amplifyframework/auth/cognito/AWSCognitoAuthPlugin.java) (dependencies of amplify-flutter) seem not providing this API. Probably need to raise feature request to both repositories.

**Comment by Jordan-Nelson** [comment]
@fpabl0 - I think this request is similar to #593. It would help to track this request under a single issue. If you feel that this request is different than #593, please let me know. Otherwise, feel free to give 593 a 👍 and leave a comment with your use case. If I do not hear back, I will close this out as a duplicate and use 593 to track this.

**Comment by fpabl0** [comment]
Hello @Jordan-Nelson, yes, you are right, they are the same. Then, I will close this in favor of #593.
