### ISSUE TITLE
Fetch Auth Session throws an unknown error Amplify 0.2.0

### ISSUE THREAD

**Issue by fdarsot** [aws-amplify/amplify-flutter#977]
Hi there,
my team and i are running on version amplify 0.2.0 and we're sure the user has logged in.

We are getting an error: "Unexpected error occurred with message: Unable to get valid sign in session from the end user."

Please assist.

**Comment by HuiSF** [comment]
Hi @fdarsot Thanks for reporting this issue. amplify-flutter 0.2.5 is the latest version that there are a few auth related issues has been fixed. Could you please test with the latest version, see if this issue persists? Thanks!

**Comment by abdallahshaban557** [comment]
@fdarsot  - are you still experiencing this issue after updating your amplify-flutter dependency?

**Comment by fdarsot** [comment]
Confirming, that i am still getting the issue. packages are fully updated

**Comment by Jordan-Nelson** [comment]
@fdarsot - This appears to be the same issue as #1042. Since that issue has had more discussion, I would like to use it to track this issue. I know you have already commented on that issue, but please feel free to give it a 👍 as well. It helps us to quickly get an idea of how many people are facing an issue.

Please let me know if you think there is any reason to keep this issue open, otherwise I will close it out.
