### ISSUE TITLE
No implementation found for method configure on channel com.amazonaws.amplify/core - on Android back button click

### ISSUE THREAD

**Issue by fjnoyp** [aws-amplify/amplify-flutter#99]
1. On Android, run the example app
1. When the LandingPage is shown with the "Sign In" and "Sign Up" buttons, hit the back button until the Android home screen is displayed.
1. Hit the Android app switcher button (rightmost) and return to the example app. App stays on the LoadingPage.
Console log shows:
E/flutter (31034): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: MissingPluginException(No implementation found for method configure on channel com.amazonaws.amplify/core)
E/flutter (31034): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:7)
E/flutter (31034): <asynchronous suspension>
E/flutter (31034): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:334:12)
E/flutter (31034): #2      MethodChannelAmplifyCore.configure (package:amplify_core_plugin_interface/method_channel_amplify.dart:25:21)
E/flutter (31034): #3      Amplify.configure (package:amplify_core/amplify_core.dart:71:35)
E/flutter (31034): #4      _MyAppState._initAmplifyFlutter (package:sample_app/main.dart:61:19)
E/flutter (31034): #5      _MyAppState.initState (package:sample_app/main.dart:52:5)
E/flutter (31034): #6      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4684:58)
E/flutter (31034): #7      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
E/flutter (31034): #8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
E/flutter (31034): #9      Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
E/flutter (31034): #10     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1174:16)
E/flutter (31034): #11     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1145:5)
E/flutter (31034): #12     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:1087:17)
E/flutter (31034): #13     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2620:19)
E/flutter (31034): #14     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1086:13)
E/flutter (31034): #15     WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:927:7)
E/flutter (31034): #16     WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:908:7)
E/flutter (31034): #17     _rootRun (dart:async/zone.dart:1182:47)

_Originally posted by @kjones in https://github.com/aws-amplify/amplify-flutter/issues/80#issuecomment-682235061_

**Comment by fjnoyp** [comment]
This issue does not happen when the app is backgrounded using the other Android bottom bar buttons.  

To reproduce, the Android **back** button must be pressed.  The app is still backgrounded but the issue occurs afterwards.

**Comment by fjnoyp** [comment]
Looking at Flutter logs, one can see an inconsistency from Flutter in how the app is "backgrounded".  If the app is backgrounded using the other Android bottom bar buttons the following lifecycle events occur: 

D/AutoSessionTracker( 8274): Activity paused: MainActivity
D/AutoSessionTracker( 8274): Activity stopped: MainActivity
D/AutoSessionTracker( 8274): Activity state saved: MainActivity
D/AutoSessionTracker( 8274): Activity started: MainActivity
D/AutoSessionTracker( 8274): Activity resumed: MainActivity

In this case the app state is still preserved.

**Comment by fjnoyp** [comment]
However, when pressing the back button, the destroy lifecycle events occurs.  At this point app state is lost and the crash will occur in the logs.  Our Flutter app is now in an inconsistent state and probably not recoverable ... 

D/AutoSessionTracker( 8274): Activity paused: MainActivity
D/AutoSessionTracker( 8274): Activity stopped: MainActivity
**D/AutoSessionTracker( 8274): Activity destroyed MainActivity**

**Comment by Amplifiyer** [comment]
This seems like an issue where the back button causes the FlutterActivity to be destroyed in Android instead of sending it to background. There are some workarounds mentioned here https://stackoverflow.com/questions/55539302/sending-your-application-to-background-when-back-button-is-pressed-in-flutter that can be used by the applications such as 
* https://medium.com/stuart-engineering/%EF%B8%8F-the-tricky-task-of-keeping-flutter-running-on-android-2d51bbc60882
* https://www.programmersought.com/article/3839440802/

We will discuss if it makes sense to provide such workarounds in the Amplify libraries or wait until Flutter provides a more standard solution.

**Comment by alextekartik** [comment]
In my experiment, this happens because cognito flutter registration fails (yes it can be called twice in this situation, see #312). Other plugins (I know for having dealing with this in my sqflite plugin) such a firebase handles this case gracefully.

**Comment by Amplifiyer** [comment]
Reopening this as we did more deep dive into this and found out the root cause that is causing this issue. It is true that flutter's activity gets killed on the back button, however on resuming the application, flutter recreates the activity. 

This assumes that the platform plugin's initialization code is idempotent which is not the case with amplify-flutter since underlying libraries can only be configured (and adding plugins) only once, repeated calls return an exception. e.g. [AnalyticsPlugin](https://github.com/aws-amplify/amplify-flutter/blob/bd5c812be380f2e079da34fb55769d14dc5b3668/packages/amplify_api/android/src/main/kotlin/com/amazonaws/amplify/amplify_api/AmplifyApiPlugin.kt#L41)

Flutter activity however [swallows the exception](https://github.com/flutter/engine/blob/68cd4c42b506dedd08fcd0d8f6d7fa101fe6c42d/shell/platform/android/io/flutter/embedding/engine/plugins/util/GeneratedPluginRegister.java#L35-L41) (no error logs printed either) and fail to initialize the platform plugins resulting in the exception mentioned in this issue.

The fix would be to make platform plugins' init code idempotent (catching and swallowing the specific exception about reconfiguration). Since the dart activity gets recreated again as well (`initState`) gets called again, amplify-flutter customers would also have to catch and ignore `AmplifyAlreadyConfiguredException` if the Amplify is being configured in the `initState`
